.github/workflows/test.yaml, azure-pipelines.yml, requirements-dev.txt
Fixes #141 #142 
- Replicate tests run in ADO to github actions
- Use pytest-xdist to enable parallel testing
- Install `wheel` in the test environments
=> Create github actions for faster CI

requirements-dev.txt
https://pypi.org/project/flake8-pyi/ catches errors in pyi stubs. We don't have pyi's yet but it's good to have the check in place.
=> Add flake8-pyi linter

.github/workflows/lint.yaml
Minimally needed permissions for actions.
Ref: https://docs.github.com/en/rest/overview/permissions-required-for-github-apps#permission-on-pull-requests
=> Limit action permissions

onnxscript/evaluator.py, onnxscript/values.py
Move ort import into functions so onnx script still works without ort. This is also more friendly for new potential evaluators that do not require ORT.
fixes: #81
=> fix: move onnxruntime import to function scope

docs/examples/03_export_lib.py, docs/examples/06_plot_model_local_funs.py, onnxscript/converter.py, onnxscript/test/functions/ort_custom_ops.py, onnxscript/test/models/cast_like.py, onnxscript/test/models/eager_op.py, onnxscript/test/models/getitem.py, onnxscript/test/models/identity.py, onnxscript/test/operator_test.py
A script function should implicitly or explicitly indicate which ONNX opset version it uses.
This PR adds a search in the converter to identify any implicit use of an ONNX opset (indicated by a call to `someopset.OpName(...)`) first. The identified opset is used, for example, in translation of overloaded operators.
For a function that contains no such call (for example, one that uses only overloaded operators such as + and *), the script parameter should specify the default_opset to use. 
Cleanup all examples where a default needs to be specified.
=> Cleanup use of default opset in converter

onnxscript/converter.py, onnxscript/test/converter_test.py
The unique-name generation mechanism does not take input parameters into account. Fix this bug.
Fixes https://github.com/microsoft/onnx-script/issues/242
=> Add input parameter names to used vars

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
Try to implement 2 ops in aten lib functions: zeros and zeros_like.
=> Add 2 ops zeros and zeros_like.

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/function_libs/torch_aten/registration.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
* __->__ #260
Registry for all atenlib functions, which supports overloading. This change implements the `torch_op` decorator for registering all functions in the ATen lib so they are discoverable. It is not designed to be used by users, but rather as an info container so code gen knows which ops are implemented.
`torch_op` also compiles the functions into OnnxFunction.
=> feat(atenlib): atenlib function registry

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py, requirements-onnx.txt
- Merge `aten_clamp_min`, `aten_clamp_max`'s scalar and tensor versions by adding logic on the input rank.
- Fix repeat on the empty `repeats` case.
Reviewers: please merge if approved
=> fix(atenlib): merge aten_clamp_min/max tensor and scalar version; repeat

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/function_libs/torch_aten/typing.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
Boolean and bitwise operators, sign, leaky relu, relu, remainder etc.
- Boolean and bitwise operators will be tested with the generated symbolic functions. 
- Define more types
- Removed tests other than float. Fixes #263
=> feat(atenlib): ops 5/n

onnxscript/type_annotation.py, onnxscript/values.py
1. While calling pytepe_to_attrtype() function, the annotation of typing.Sequence will be identified to collections.abc.Sequence by get_origin(). This will impact the further execution, so adding collections.abc.Sequence into the _LIST_CONSTRUCTORS.
2. While calling a function in eager mode, a list type of input should not be transformed to be a Tensor list. Update the code logic accordingly.
=> Fix type annotation issue of Sequence and fix a list issue in eager mode.

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
upsample_nearest2d, amax, amin and adaptive pools
upsample_nearest2d was tested locally on opset17. Opset18 cannot be tested yet because onnx runtime does not support it yet.
=> feat(atenlib): ops 7/n

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/registration.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
Implement `aten_index_select`; enable tests for transpose.
This change also added the **`trace_only`** argument to mark functions as trace only to work around functions that cannot be compiled. The logic can then be tested, but the argument should be removed later when onnxscript extends support for the syntax.
=> feat(atenlib): index_select; trace_only ops

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/typing.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
=> feat(atenlib): arange with overloads

onnxscript/function_libs/torch_aten/ops/core.py
Fix "onnxscript/test/function_libs/torch_aten/ops_correctness_test.py::TestOutputConsistencyCPU::test_output_match_full_cpu_float32 - RuntimeError: Unable to create onnxruntime InferenceSession for executing .Expand op with onnx model
<print utility unavailable>" on Windows.
=> fix(atenlib): cast size to int64 in aten_full

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/common/testutils.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py, onnxscript/test/type_annotation_test.py, onnxscript/type_annotation.py
~~Concern on the annotation of `k` as `int`. I assume this would imply static value in onnx/onnxscript? Since scalars could be non-static in torch, would we want a scalar type wrapper too?~~ Answer is use `INT64`.
* Add `aten_topk`.
* Extend onnx script type annotation for bool argument for attributes.
* Extend opinfo test for multiple outputs.
Fixes #283
=> feat(atenlib): topk; bool argument type annotation; node of multiple outputs

azure-pipelines.yml, onnxscript/test/functions/onnxfns2_test.py, onnxscript/test/models/onnxfns2.py, requirements-onnx.txt
Root cause is new "Reduce ops" spec promotes `axes` from attributes to inputs, resulting in onnx test cases having more inputs than expected by these onnx-script tests. This PR updates these onnx-script test functions to match the signature of the updated onnx test cases.
However, since onnx test cases are not versioned, I feel tests like this that seemingly want to represent ~~older opset~~ onnx operator with function should not depend on it.
Fixes #249 
Fixes #298
=> Fix onnxfs2_test regression for onnx 1.13

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py, onnxscript/test/onnx_backend_test.py, pyproject_pylint.toml
Split the scripted and traced ops and added a test to make sure we compiled all functions.
=> test(atenlib): split mappings to two

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
Add a new op embeding and its test.
=> Add a new op embedding.

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py, onnxscript/values.py
1. Add 2 new ops: permute and pow.
2. Fix (partially) #287: convert the values of attributes from tensor back to numpy value when we call Op.
=> Add permute and pow ops and fix attribute value issue.

codecov.yml, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py, pyproject.toml
This should fix #309. Green ci 1/2.
Also set codecov to be informational only so CI status is not affected
=> test(atenlib): explicitly convert ints to int64

.github/workflows/lint.yaml
Do not submit sarif on drafts to make reviewing easier, but always run lintrunner.
Follow up of #326
=> fix(ci): do not submit sarif on drafts to make reviewing easier

onnxscript/function_libs/torch_aten/ops/core.py
previous implementation is greater not greater and equal. fixes #315
=> fix(atenlib): GE and LE op

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
using opset17 inside the function to pass the testing, due to opset18 is not ready yet.
=> feat(atenlib): add ops(native_layer_norm)

onnxscript/evaluator.py, onnxscript/main.py, onnxscript/tensor.py, onnxscript/test/tensor_test.py, onnxscript/values.py
Update the evaluator and tensor's interfaces for graph capturing evaluators.
- Add `eval_function` to Evaluator and calls it from functions
- Add `rank` to `Tensor`
- Make all helper functions in evaluator private
=> feat: generalized `Evaluator` and `Tensor` interfaces

onnxscript/converter.py, onnxscript/test/converter_test.py
The introduction of CastLike automatically around constants was not handling attributes promoted into constants. This PR fixes this.
=> Extend auto cast-like for attributes

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
add op: sum with trace_only = True, due to OptionalHasElement() cannot work now
=> feat(atenlib): add ops(sum)

onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
aten_cat does not support zero-dim tensors yet
=> fix(atenlib): skip test case with empty tensors for cat

onnxscript/evaluator.py, onnxscript/values.py
Move user mode adaptation to inside Evaluator to allow evaluators to override the value adaptation behavior. For example, `TorchScriptEvaluator` prefers inputs to be raw python values and handles constant creation inside its graph.
=> feat(eager): move user mode adaptation to inside evaluators

onnxscript/autocast.py, onnxscript/evaluator.py
This matches numpy and torch's behavior on linux
```
In [4]: np.array(1).dtype
Out[4]: dtype('int64')
In [6]: torch.tensor(1).dtype
Out[6]: torch.int64
```
- Also adds bool type to autocast
- Add typing information to autocast
=> fix(autocast): default int to int64

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/function_libs/torch_aten/ops/sparse.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
- Simplify logic in `add`, `conv2d`.
- Update all float attribute defaults to actual floating-point numbers instead of ints. 
- Fix `linear` logic (transpose weight) and enable tests
- Fix clamp
- Fix amin amax
- Fix native_layer_norm
- Fix slice
- Fix where signature
- Fix full
- Fix sub
Ops that uses ReduceMin and ReduceMax are currently on opset17, as onnxruntime does not support them and we want to use ort to run fx tests.
=> fix(atenlib): clean up ops and fix errors

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Use `onnx.checker.check_function` to check functions are valid; fixed errors found
- Improve the trace_only test assertion messages
=> fix(atenlib): test function with checker and fix errors

onnxscript/function_libs/torch_aten/graph_building.py
[fake_gpt.py](https://github.com/pytorch/pytorch/blob/onnx-team/dynamo-exporter/torch/onnx/_internal/docs/fake_gpt.py) might add None as input for graph builder. Further looking into it, it seems just a bug, as we already defined a if branch for None value.
=> integrate with fake_gpt.py

onnxscript/function_libs/torch_aten/graph_building.py, onnxscript/function_libs/torch_aten/ops/core.py
- Support adding BOOL constants in graph_builder
- Fix type error in `_aten_convolution_onnx` where the `cond` to if is `int64` if `transposed` were an attribute
- Enable model checker in TorchScriptGraph
=> feat(atenlib): enable model checker in TorchScriptGraph

noxfile.py, onnxscript/backend/onnx_export.py, onnxscript/tests/external_tensor_test.py, pyproject.toml
autopep8 is slow. We remove it and eventually should move to use Aaron's code gen module.
=> chore: remove autopep8

onnxscript/function_libs/torch_aten/graph_building.py
Previously we don't use domain to deduplicate functions. This may cause functions that share the same name to overwrite each other.
=> fix(atenlib): add domain as part of key to onnx function store

onnxscript/evaluator.py, onnxscript/function_libs/torch_aten/graph_building.py
Make Evaluator a Protocol and change the old evaluator into BaseEvaluator. This way other evaluators like TorchScriptEvaluator that does not require input adaptation don't need to carry all the base methods. It also frees them from having to implement the indirect `_eval` method, making the programmatic api cleaner.
=> feat(eager): turn Evaluator into a Protocol

onnxscript/function_libs/torch_aten/ops/core.py
Create a bool overload for bitwise_not and fix an incorrect cast in maskd_fill
Discovered when running bloom export.
=> fix(atenlib): bitwise_not and maskd_fill

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Test for new_empty was flaky because it doesn't always fail. Changed to skip
=> fix(atenlib): flaky test for new_empty

.lintrunner.toml, pyproject.toml
Enable `TID252` in ruff but allow relative imports in init files.
=> chore(lint): disallow relative imports

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Check shape and dtype only for ops that are known to be indeterministic.
Also added the skip_if mechanism to skip tests based on environment.
=> feat(atenlib): test random ops

onnxscript/converter.py, onnxscript/converter_test.py
Extend the converter to support attribute-values that are None (in actual parameter list). Currently, it requires users to omit such attribute values instead of specifying a value of None.
=> Support none-valued attribute parameter

onnxscript/function_libs/torch_aten/graph_building.py, onnxscript/function_libs/torch_aten/graph_building_test.py
=> Merge 'initializers' into 'TorchScriptGraph'

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Enable -1 test for op.Expand
Should be included in https://github.com/microsoft/onnx-script/pull/507
=> enable -1 test in expand

noxfile.py, onnxscript/backend/onnx_export_test.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py, onnxscript/tests/functions/onnxfns2_test.py
I saw an error comes from certain Python 3.9 CI pipeline: `'/Users/runner/work/onnx-script/onnx-script/.nox/test/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))`, which is fixed by the latest ONNX Runtime 1.14.1: https://github.com/microsoft/onnxruntime/issues/14663. Bumping onnxruntime version here should help. Meanwhile, also try to bump onnx and torch to the latest patch release, which should be harmless.
=> fix(test): bump onnxruntime, onnx, torch versions in noxfile.py

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
aten::trunc
```
<
domain: "onnxscript.atenlib",
opset_import: ["" : 18]
>
aten_trunc (self) => (return_val)
{
tmp = Abs (self)
integer_parts = Floor (tmp)
tmp_0 = Constant <value = float tmp_0 {0}> ()
tmp_0_cast = CastLike (tmp_0, self)
is_negative = Less (self, tmp_0_cast)
tmp_1 = Neg (integer_parts)
return_val = Where (is_negative, tmp_1, integer_parts)
}
```
=> feat(atenlib): op(trunc)

onnxscript/function_libs/torch_aten/graph_building.py, onnxscript/function_libs/torch_aten/graph_building_test.py, onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/tensor.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Test TorchScriptEvaluator by capturing function protos and the full graph and executing the model with ORT. Only runs on torch-nightly.
Parameterize the TestOpConsistency body to run in both eager mode and graph mode.
Fix
- Remove opset17 reference
- amin
- amax
- native_layer_norm
- dropout
`OptionalGetElement` is not mature enough to use right now. We need to fix shape inference to use it.
Others are marked as xfail for now to fix in future PRs.
=> chore(test): test atenlib with TorchScriptEvaluator

noxfile.py, requirements-dev.txt
https://pypi.org/project/pytest-randomly/
Tests are still reproducible locally by supplying the random seed from CI:
> Randomness in testing can be quite powerful to discover hidden flaws in the tests themselves, as well as giving a little more coverage to your system.
>
> By randomly ordering the tests, the risk of surprising inter-test dependencies is reduced - a technique used in many places, for example Google’s C++ test runner googletest. Research suggests that “dependent tests do exist in practice” and a random order of test executions can effectively detect such dependencies [1]. Alternatively, a reverse order of test executions, as provided by pytest-reverse, may find less dependent tests but can achieve a better benefit/cost ratio.
=> chore(ci): run tests in random order

.github/workflows/lint.yaml, .lintrunner.toml, onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/function_libs/torch_aten/registration.py
Currently private functions are marked as `overload`s. Since private functions (anything starts with `_`) will never be dispatched onto by the exporter, we can create a new label `private` to register them differently.
Fixes https://github.com/microsoft/onnx-script/issues/504
=> feat(atenlib): create a `private` tag for private functions

onnxscript/function_libs/torch_aten/graph_building.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
This PR adjusts the test code to be able to handle the output of `torch.split` and adds support for sequence as input. Note that this is different from the exporter's concat for symints, because at the point when we have inputs processed and still get list of Tensors as a single argument, we know it should be an ONNX Sequence tensor in the graph.
We also need to keep the addition in here and not in the exporter to match behavior with onnxscript eager: we accept a list of tensors as input when the op takes a Sequence.
=> fix(atenlib): test split and support Sequence input

noxfile.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Use PyTorch 2.0 to run tests. Bump aten lib minimal pytorch version to 2.0
=> chore(ci): use PyTorch 2.0

onnxscript/function_libs/torch_aten/graph_building.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
1. Initializer must be an input. Otherwise, there is no torch._C.Value to repreent it in torch._C.Graph.
2. Shape inference fails for custom op, so it should be optional until we fix it.
=> fix(graph_building): change `add_initializer` to return a Tensor; make shape inference optional

onnxscript/function_libs/torch_aten/ops/core.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
=> feat(atenlib): addOp(new_ones, new_zeros)

onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
torch nightly (torch 2.0) CI failed
=> feat(atenlib): add Op(mse_loss)

onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py, onnxscript/values.py
- Fix static optional support in ParamSchema
- Make `cross_entropy_loss` a script function
Follow up of https://github.com/microsoft/onnx-script/pull/444/files#diff-647f5c6f5a51c850e0a6bfd534cc8d1357d5b617c432693af121830b65a324c2R242
=> fix(atenlib): combine cross_entropy_loss

onnxscript/onnx_opset/__init__.py, opgen/onnx_opset_builder.py
Otherwise pylance/intellisense shows inferred type `dict[tuple[Literal[''], Literal[1]] | tuple[Literal[''], Literal[2]] | tuple[Literal[''], Literal[3]] | tuple[Literal[''], Literal[4]] | tuple[Literal[''], Literal[5]] | tuple[Literal[''], Literal[6]] | tuple[Literal[''], Literal[7]] | tuple[Literal[''], Literal[8]] | tuple[Literal[''], Literal[9]] | tuple[Literal[''], Literal[10]] | tuple[Literal[''], Literal[11]] | tuple[Literal[''], Literal[12]] | tuple[Literal[''], Literal[13]] | tuple[Literal[''], Literal[14]] | tuple[Literal[''], Literal[15]] | tuple[Literal[''], Literal[16]] | tuple[Literal[''], Literal[17]] | tuple[Literal[''], Literal[18]] | tuple[Literal[''], Literal[19]] | tuple[Literal['ai.onnx.ml'], Literal[1]] | tuple[Literal['ai.onnx.ml'], Literal[2]] | …
=> Type annotate 'all_opsets'

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
ORT matmul produces nan on inputs with zero elements nondeterministically.
Fixes #538
=> Skip a flaky matmul test | test(atenlib)

pyproject.toml, requirements-dev.txt
setuptools needs to be >= 61.0.0 to understand pyproject. Making this clear in requirements.
=> Specify setuptools version | chore(release)

noxfile.py, requirements-dev.txt
=> Remove click as a requirement | chore(release)

onnxscript/function_libs/torch_aten/ops/core.py
Fix typing annotation to be compatible with python 3.8, because `tuple[]` cannot be a generic type until 3.9. Also updated the aten name to match the signature
=> Improve `max_pool2d_with_indices` | fix(atenlib)

pyproject.toml
It was not the intended license. Now changed to point to the LICENSE file
=> Fix license in pyproject.toml | chore(release)

onnxscript/function_libs/torch_aten/ops/nn.py
Previously the functions where not properly registered, causing their domains to become `"this"`
Fixes #608
=> Fix domains for aten_scaled_dot_product_attention | fix(atenlib)

onnxscript/function_libs/torch_aten/ops/nn.py, onnxscript/tests/function_libs/torch_aten/extra_opinfo.py, onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
1. Add max_pool3d and max_pool3d_with_indices ops.
2. Refactor the code so max_pool2d and max_pool3d could share the same helper function. And move them to nn.py file.
3. Refactor the code so max_pool2d_with_indices and max_pool3d_indices could share the same helper function. And move them to nn.py file.
4. Add tests.
=> Add ops(max_pool3d and max_pool3d_with_indices) | feat(atenlib)

onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Temporarily disable tests for scaled_dot_product_attention because ORT segfaults on linux. #567
=> Disable tests for scaled_dot_product_attention | ci(atenlib)

onnxscript/converter_test.py, onnxscript/tests/common/testutils.py, onnxscript/tests/if_test.py, onnxscript/tests/loop_test.py, onnxscript/tests/operator_test.py, onnxscript/type_annotation_test.py
Clean up test cases. Remove `assertSame*` methods from the TestBase in favor of the public onnxscript.testing module.
- Removed all skips that checks for onnx<1.13 because we now run 1.13 as the lowest version.
=> Make test cases use `onnxscript.testing` | chore(testing)

.github/workflows/release.yaml
Add `--no-deps` to release.yaml so it doesn't reacquire onnx.
=> Add `--no-deps` to release.yaml | chore(release)

.lintrunner.toml, requirements-dev.txt
So running `lintrunner` now means `lintrunner -m main`, which is easier.
https://github.com/suo/lintrunner/commit/75ea9c09cd6904e6e53170af0661fd3dcb39c9e9#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fc
=> Update .lintrunner.toml to include a merge base | chore

onnxscript/converter_test.py, onnxscript/tests/eager_test.py, opgen/onnx_opset_builder.py, pyproject.toml
Enable to ISC rules to check to error prone concatenations
=> Enable string concatenation checks in ruff | chore(lint)

onnxscript/backend/onnx_export.py, onnxscript/converter_test.py, pyproject.toml
flake8-logging-format (G), flake8-comprehensions (C4)
=> Enable G and C4 rules in ruff | chore(lint)

onnxscript/function_libs/torch_aten/graph_building.py
Create repr so it doesn't show as `TorchScriptTensor(None)`
=> Display name/shape info in TorchScriptTensor | feat(graph_building)

.github/workflows/lint.yaml
Add the `security-events: write` permission to lint for it to be able to upload the sarif file.
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository
Fixes #652
=> Add permission to the lint job

onnxscript/function_libs/torch_aten/ops/nn.py
We should cast the mask to float for the logic to be correct.
Fixes #580
=> Fix attention logic when mask is boolean | fix(atenlib)

.lintrunner.toml, requirements-dev.txt, requirements/lintrunner/requirements.txt
RUFF can now format since lintrunner-adapters v0.8. Removed the RUFF-FIX linter
=> Enable RUFF as a formatter | chore(lint)

.github/workflows/main.yaml, noxfile.py
- Updated the torch-nightly action to also use onnx-weekly, so we can run op tests with torch-nightly.
- Remove the function experiment test because microsoft/onnxruntime#14929 was merged
=> Update test pipelines | chore(ci)

.github/workflows/main.yaml, onnxscript/_internal/feature_switch.py, onnxscript/evaluator.py
Try to disable ort session cache to avoid Windows memory exception caused by CI tests.
Fix #614
=> Add an environment variable to disable ort session cache if necessary | fix(atenlib)

onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, requirements/ci/requirements-pytorch-nightly.txt
This requires ONNX 1.14. I am skipping the op test for ONNX<1.14 altogether.
I tested locally to make sure no float32 test is skipped with this mechanism, and that it skips properly according to the type annotation.
Currently no new dtypes are enabled because there are too many failures.
Requires 
- #701 
- #698
=> Skip incompatible dtypes in op_test using OpSchema | test(torchlib)

onnxscript/evaluator.py, onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
The previous implementation is based on op17. For op18, using op.Split() by specified num_outputs attribute.
This change updates the graph builder to create a correct number of outputs for Split when num_outputs is specified.
Closes #622
=> Refine op(chunk) | feat(atenlib)

onnxscript/function_libs/torch_lib/ops/nn.py
=> Add output types to attention | fix(torchlib)

.github/codeql/codeql-config.yml
Module level cyclic import, although should be avoided if possible, is not a problem from the perspective of functionality. It is more preferable than hiding imports in functions from a readability and maintainability point of view.
=> Disable `py/cyclic-import` in codeql

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/function_libs/torch_lib/registration.py
After this PR, overloads is deleted, and when we register a **aten overload**, we use it's specific name: `aten::mean.dim`. If it's an **onnx overload** created regarding ONNXFunction limitations, such as `aten_bitwise_not_bool`, we can simply register it under the same aten name. The dispatcher in converter side is expected to find the proper one with op schema.
=> Refactor Overloads | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Refine aten_isfinite by adding cast at beginning, so it can support all float dtypes.
The original implementation 'self: Union[FLOAT, DOUBLE]' is only for skip the testcase. When used with FP16, it will failed.
I wrote some Notes in ops_test_data.py, just like:
```python
OPINFO_FUNCTION_TARGET_DTYPE: dict[
str,
tuple[Any, ...],
] = {
...
```
We have a list, so we can know the functions those we made this kind of change.
If we have some other better solutions that can support this scenario, we can also revert this change.
=> RefineOpForFP16(2)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
It wasn't following aten signature, so it's unusable on converter side.
Based on the agreement: https://github.com/microsoft/onnxscript/pull/582#discussion_r1154491445
=> Refactor op(scatter add) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Below 2 Ops works well on FullGraph mode, but have precision loss on Eager mode.
1. op(log_sigmoid), using (5e-3, 3e-4) as rtol and atol. Becuase numpy also give same result as ORT on float16.
for example: x=3.8242, y=np.log(1/(1+np.exp(x))=?
with float32: y = -0.0216
with float16: y = -0.02122
2. op(remainder), the difference is too big between float32 and float16, so we have to cast to fp32 at very beginning to avoid accuracy loss.
e.g. self=7.7500, other=0.1582
in float32 mode: result = 0.1562
in float16 mode: result = 0.0
Numpy has same behaviour.
=> Refine op for fp16(3)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/graph_building_test.py
Extend `TorchScriptGraph` to allow the concept of nested graphs. When serializing,
the root graph serializes to `ModelProto`, while all sub graphs are serialized as `FunctionProto`.
=> Model local function building | feat(graph_building)

onnxscript/function_libs/torch_lib/ops/nn.py
Found this bug when I try to apply this op in a model (https://github.com/pytorch/pytorch/pull/102773). Basically, if the input padding is 3d, we still need to double it to fit the ONNX requirement that we need begin and end padding. I am not sure why we didn't catch this in ops_test.py though, it seems should be caught...
=> Fix op (MaxPool) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
op.SequenceMap comes to the rescue for element iteration cases. (Maybe it's just me that didn't know this...)
This PR helps complete #762
=> App op (atleast_1d and atleast_2d and atleast_3d) | feat (torchlib)

onnxscript/irbuilder.py, requirements/ci/requirements-onnx-weekly.txt
Replaces #750, resolves CI issues.
Needed by https://github.com/pytorch/pytorch/pull/101029 in order for onnxscript to work with latest onnx.
The PyTorch PR needs bugfix https://github.com/onnx/onnx/commit/213b525a51ead28961d9b4f2764b08c7e336bf2c in ONNX.
Preferrably waits for onnx 1.15 or 1.14.1.
=> Fix 'attr_proto' with latest onnx, bump onnx-weekly | chore(deps), fix(irbuilder)

onnxscript/onnx_opset/_impl/opset1.py, onnxscript/onnx_opset/_impl/opset10.py, onnxscript/onnx_opset/_impl/opset11.py, onnxscript/onnx_opset/_impl/opset12.py, onnxscript/onnx_opset/_impl/opset13.py, onnxscript/onnx_opset/_impl/opset14.py, onnxscript/onnx_opset/_impl/opset15.py, onnxscript/onnx_opset/_impl/opset16.py, onnxscript/onnx_opset/_impl/opset17.py, onnxscript/onnx_opset/_impl/opset18.py, onnxscript/onnx_opset/_impl/opset2.py, onnxscript/onnx_opset/_impl/opset3.py, onnxscript/onnx_opset/_impl/opset4.py, onnxscript/onnx_opset/_impl/opset5.py, onnxscript/onnx_opset/_impl/opset6.py, onnxscript/onnx_opset/_impl/opset7.py, onnxscript/onnx_opset/_impl/opset8.py, onnxscript/onnx_opset/_impl/opset9.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml1.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml2.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml3.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_preview_training1.py, opgen/onnx_opset_builder.py
Given a hypothetical `OpSchema` _Thing_ that has two identically type-constrained inputs and a type constrained output:
```
inputs:
T1: tensor(int32), tensor(int64)
T2: tensor(int32), tensor(int64)
outputs:
T1
```
We were previously ignoring the type constraint itself, which is problematic especially when the return type should be the same type as one of the constrained arguments, since this is unsolvable.
```python
def Thing(a: Union[INT32, INT64], b: Union[INT32, INT64) -> Union[INT32, INT64]:
...
Thing(some_INT64_tensor, some_INT32_tensor)
```
This PR addresses the issue by translating type constraints on the schema into proper `typing.TypeVar` usage:
```python
T1 = TypeVar("T1", INT32, INT64)
T2 = TypeVar("T2", INT32, INT64)
def Thing(a: T1, b: T2) -> T1:
...
Thing(some_INT64_tensor, …
```
=> opgen: translate type constraints in an OpSchema to typing.TypeVars in the static API

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Missing operator: https://github.com/microsoft/onnx-converters-private/issues/168
Follow up issue track: https://github.com/microsoft/onnxruntime/issues/16296
=> Add op (hsatck & vstack) | feat(torchlib)

requirements-dev.txt, requirements/ci/requirements-onnx-weekly.txt
Tests were failing locally in an environment with `onnx-weekly` already installed after re-running `pip install -r requirements-dev.txt`.
=> requirements: bump onnx-weekly>=1.15.0.dev20230605

onnxscript/_internal/param_manipulation.py, onnxscript/evaluator.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/irbuilder.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py, onnxscript/values.py, onnxscript/values_test.py
* #759
* __->__ #758
Preserves original arguments order for param_schemas, including when OnnxFunction 
is defined with intersecting inputs and attrs. E.g. `def function(self, input1, attr1, input2, attr2)`.
`eval_function` for `TorchScriptTracingEvaluator` is left unchanged, i.e., splits arguments into inputs
and attributes. Because that is the format expected by TorchScript graph building.
Fixes #277 Fixes #305
=> Preserve correct params order in FunctionIR

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Now that we support mixed input/attribute ordering from #758
=> Remove trace_only for scatter_add | chore(torchlib)

onnxscript/autocast.py
`isHomogeneous` and `typeStr` are deprecated
=> Remove deprecated usage in onnx | fix(autocast)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/onnx_opset/_impl/opset1.py, onnxscript/onnx_opset/_impl/opset10.py, onnxscript/onnx_opset/_impl/opset11.py, onnxscript/onnx_opset/_impl/opset12.py, onnxscript/onnx_opset/_impl/opset13.py, onnxscript/onnx_opset/_impl/opset14.py, onnxscript/onnx_opset/_impl/opset15.py, onnxscript/onnx_opset/_impl/opset16.py, onnxscript/onnx_opset/_impl/opset17.py, onnxscript/onnx_opset/_impl/opset18.py, onnxscript/onnx_opset/_impl/opset19.py, onnxscript/onnx_opset/_impl/opset2.py, onnxscript/onnx_opset/_impl/opset3.py, onnxscript/onnx_opset/_impl/opset4.py, onnxscript/onnx_opset/_impl/opset6.py, onnxscript/onnx_opset/_impl/opset7.py, onnxscript/onnx_opset/_impl/opset8.py, onnxscript/onnx_opset/_impl/opset9.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml1.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml2.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_ml3.py, onnxscript/onnx_opset/_impl/opset_ai_onnx_preview_training1.py, onnxscript/tests/eager_mode_test.py, opgen/onnx_opset_builder.py
> ⚠️🚨🔥 ***Note:*** this is an API break since all attributes are now keyword-only, so positional usage is no longer allowed. Our tests uncovered a handful of places where we were specifing attributes as positional arguments.
By explicitly projecting all OpSchema attributes to keyword-only arguments in Python, we do not need to reorder attributes based on whether or not they have default values. This allows the Python API to express the same ordering as the op itself for inputs and attributes.
This also makes attribute specification consistent with variadic input ops which already have that implicit requirement.
=> opgen: make all OpSchema attributes keyword-only args in Python

onnxscript/function_libs/torch_lib/graph_building.py
Needed by https://github.com/pytorch/pytorch/pull/103865/
When a PyTorch model is traced using `FakeTensor` weights[1], the resulting IR will not actually contain Tensors that can be serialized into protobuf.
In that scenario, the model must be serialized without any initializer to prevent invalid data access on the underlying PyTorch tensor. This PR proposes an optional parameter `include_initializers: bool = True` to `to_model_proto` API for allowing the serializer to ignore any initializer during serialization.
[1] `FakeTensor` is a subclass of `Tensor`, but without the actual data. See below for an example:
```python
{'_param_constant0': Parameter(FakeTensor(..., size=(2, 2), requires_grad=True)),
'_param_constant1': Parameter(FakeTensor(..., size=(2,), requires_grad=True))}
```
=> Add support for serialization without initializers

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
`aten.tensor` is emitted from TypePromotionPass in dynamo onnx exporter.
=> Add ops (tensor.int, tensor.float, tensor.bool) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/tensor_typing.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
We always operate on the real representation of a complex number in torchlib. So view_as_real/view_as_complex are no-op. This PR additionally implements other view* ops.
=> Add ops (view*) | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
Make beartype optional by using the internal runtime_typing decorator.
fixed #821
=> Make beartype optional | chore(torchlib)

onnxscript/tests/function_libs/torch_lib/ops_test_common.py
ORT requires providers to be explicitly supplied when creating an inference session.
cc @wschin
=> Explicitly supply providers to ORT InferenceSession | test(torchlib)

onnxscript/converter.py, onnxscript/converter_test.py
Fix the translation of `return Y, Y`. Since ONNX does not allow duplicate output names, we need to insert an extra copy via Identity in such cases.
Add test-case for the same.
=> Ensure no duplicate output names

onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
There is builtin test for the PyTorch op `bernoulli`. We should use that to ensure consistency with PyTorch.
Also updated deterministic tests for bernoulli_p.
cc @wschin
=> Use the builtin bernoulli test | test(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
This op is used in llama when capturing graph using dynamo.
=> Implement aten._local_scalar_dense | feat(torchlib) 

onnxscript/converter.py, onnxscript/converter_test.py
`generate_unique_name` was not being called along one path in the translation of index-expressions. (See https://github.com/microsoft/onnxscript/issues/848 ). Fix the bug.
=> Ensure names are unique

onnxscript/function_libs/torch_lib/ops/core.py
I tested with 
```python
@torch_op("aten::bernoulli.p")
def aten_bernoulli_p(self: TTensor, p: float) -> TTensor:
"""Proximal implementation of aten::bernoulli.p(Tensor self, float p, *, Generator? generator=None)
Ignore `generator` due to the limit on ONNX expressiveness.
"""
self_shape = op.Shape(self)
p = op.Cast(p, to=FLOAT.dtype)
probs = op.Expand(p, self_shape)
sampled = op.Bernoulli(probs)
return op.CastLike(sampled, self)
```
But the results don't match with torch
=> Simplify bernoulli implementation | fix(torchlib)

onnxscript/function_libs/torch_lib/registration.py
* #864
* __->__ #863
To support registering aliases and overloads of an op, `torch_op` can now take a tuple. #828
=> Allow functions to be registered to multiple names | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/graph_building_test.py
Previously the code path is never triggered due to another bug in exporter that initializers are always added with unique names.
=> Properly check and guard overloading initializer name | fix(graph_building)

onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Rename all with the `op.aten.` prefix in extra_opinfos. This way OpInfo will find the op automatically without us having to specify the op. Also simplify the custom OpInfo to remove redundant information.
Fixes #870
=> Rename extra opinfo names and simplify the OpInfos | test(torchlib)

onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Because ORT randomly aborts on these tests on Windows. ORT is also flaky on Linux/MacOS, but it is much rarer.
https://github.com/microsoft/onnxscript/issues/761, https://github.com/microsoft/onnxruntime/issues/16492
=> Skip reduce min/max ops on Windows | test(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
`aten::max` was implemented as a big trace_only function. This change breaks it into multiple overloads like we did for `aten::min`.
- Also merged `aten::max/min.other` with `aten::minimum/maximum` as an alias.
=> Break aten::max into overloads | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/nn.py
Fix avg_pool2d to account for when `stride` is empty. Previously it was checking for None, which was not a valid input. Now checking for emptiness instead.
Tested with
```python
import torch
import onnxruntime
def func(x):
return torch.nn.functional.avg_pool2d(x, 4)
export_output = torch.onnx.dynamo_export(func, torch.randn(1, 64, 32, 32))
onnxruntime.InferenceSession(export_output.model_proto.SerializeToString())
```
Exported graph:
```
ir_version: 8
producer_name: "pytorch"
producer_version: "2.1.0"
graph {
node {
input: "arg0"
output: "avg_pool2d"
name: "AveragePool_0"
op_type: "AveragePool"
attribute {
name: "auto_pad"
s: "NOTSET"
type: STRING
}
attribute {
name: "ceil_mode"
i: 0
type: INT
}
attribute {
name: "count_include_pad"
i: 1
type: INT
}
attribute {
name: "kernel_shape"
ints: …
```
=> Fix strides for avg_pool2d when it is empty | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
WIP: need more tests
Gather op:
- https://github.com/openxla/xla/blob/main/docs/operation_semantics.md?rgh-link-date=2023-07-13T01%3A09%3A16Z#gather
- https://www.pathpartnertech.com/gather-scatter-operation-in-deep-learning-framework/
=> Implement aten::index | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
* #883
* #882
* __->__ #881
The torchscript ONNX graph generator creates numeric value names by default (`0`, `1`). These are not legal ONNX tensor names, since ONNX requires the names to be valid C variable names. This change updates the names by prepending a prefix `_val_` or `_const_` to make them valid ONNX names. It also improves readability by making the names less likely to be confused with shape values.
I decided to use the `_` prefix to reduce the chance of name collision with FX names.
After:
```
<
ir_version: 8,
opset_import: ["" : 18],
producer_name: "pytorch",
producer_version: "2.1.0"
>
torch_jit (float[5,5,5,5] input_0, int64[2] input_1_3) => (float[5,5,5,2] _val_10) {
_val_2 = Transpose <perm = [0, …
```
=> Rename intermediate values to `_val` and `_const` | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
Since torchscript graph transformation is no longer needed in the exporter, we remove the `apply` function and support for transforming torchscript graphs.
=> Remove the `apply` method in `TorchScriptGraph` | feat!(torchlib)

onnxscript/converter.py
A few converter methods were returning either a ConverterExpression or a string. Ensure that they uniformly return a ConverterExpression.
=> Return converter expression uniformly

.github/workflows/release.yaml, pyproject.toml
Because onnxscript is owned. Also updated to use trusted publisher: https://docs.pypi.org/trusted-publishers/using-a-publisher/
=> Temporarily rename package to onnxscript-preview during release | chore(release)

onnxscript/autocast.py, onnxscript/converter.py, onnxscript/converter_test.py
Cleanup following aspects of the translator:
* `ConverterExpression` was being misused to cover 0, 1, or more ONNX variables created during translation. The resulting type-annotations were unclear and the code was fragile in a few places. It now is used to represent a single ONNX variable.
* The translation of multiple-variable assignments, like `x, y, z = op.SomeOp(...)` has been refactored.
* `translate_bool_op_expr` was not using the suggested target name (the original python variable name) for generated onnx variable. Fix this.
* Fix `translate_subscript_expr` so that it returns a `ConverterExpression`, rather than a string, for uniformity.
=> Cleanup translator

onnxscript/converter.py, onnxscript/converter_test.py, onnxscript/tests/operator_test.py
Removing support for boolean operators, as discussed in https://github.com/microsoft/onnxscript/pull/896 
This only removes the support for expressions like `X and Y`, which must instead be specified as `op.And(X, Y)`. The reason is that the shorthand notation cannot be supported in eager-mode easily. (It works for the scalar-case, but not for element-wise boolean ops on non-scalar tensors. Further, python uses short-circuit evaluation for these expressions, which will also cause a divergence in behavior with respect to the translated code.
=> Remove support for boolean operators 'and' and 'or'

onnxscript/function_libs/torch_lib/ops/core.py
In torchbench we see errors like `[ONNXRuntimeError] : 10 : INVALID_GRAPH : Load model from bench_dynamo_onnx_model/attention_is_all_you_need_pytorch/model.onnx failed:This is an invalid model. Type Error: Type 'tensor(bool)' of input parameter (unsqueeze_1) of operator (BitwiseAnd) in node (n0__9) is invalid.`
This change fixes them by registering the Boolean variants from the exiting logical* implementations.
The reason for not creating new bitwise* variants is that the implementation is exactly the same as the logical* ones, which are covered by test cases. The bool bitwise* BOOL variants, if implemented separately, besides completely identical logic, would require test case duplication, which imo is not worth it.
=> Add BOOL variants to bitwise ops | fix(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
Use `_val` for all intermediate values to avoid ambiguity based on comment: https://github.com/microsoft/onnxscript/pull/881#pullrequestreview-1533418604
=> Change `_const` prefix to `_val` | feat(torchlib)

noxfile.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py, requirements-dev.txt
We may still want to run tests even if they are flaky. This PR uses pytest-rerunfailures to rerun flaky tests so they are tested.
=> Mark tests as flaky and enable reruns | test(torchlib)

noxfile.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py, requirements-dev.txt
Reverts microsoft/onnxscript#911
No rerun was triggered. Need more testing.
=> Revert "Mark tests as flaky and enable reruns | test(torchlib)"

onnxscript/function_libs/torch_lib/ops/linalg.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Also updated the should_skip_xfail logic in test to account for data types.
Have to skip one kind of test case: ord=6, dtype=float16.
In Pytorch:
```
>>> b
tensor([[2.3730, 0.9316, 0.6240, 6.1523, 0.1758],
[5.3984, 7.9375, 4.9062, 1.8809, 6.1016],
[4.0234, 8.2344, 3.2695, 0.8701, 1.3447]], dtype=torch.float16)
>>> la.vector_norm(a, dim=0, ord=6)
tensor([5.5483, 9.0838, 4.9754, 6.1532, 6.1017])
>>> la.vector_norm(b, dim=0, ord=6)
tensor([5.5469,    inf, 4.9727, 6.1523, 6.0977], dtype=torch.float16)
>>>
```
But in ORT, the result is:
```
tensor([5.5469,  9.08, 4.9727, 6.1523, 6.0977], dtype=loat16)
```
the second element ```9.08``` should be ```inf```. It works in eager mode, failed in FullGraph mode only.
=> AddOp(linalg_vector_norm) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
* #920
* __->__ #919
Resolves most reported missing overloads from https://github.com/microsoft/onnxscript/issues/865
=> Add overlooked overload information on torchlib functions

onnxscript/function_libs/torch_lib/graph_building.py
* __->__ #922
Retrieving torch dtype is slow due to fetching 'JitScalarType' through
pybind.
In a recent change in PyTorch exporter, this method is invoked heavily
to produce diagnostic info for operator arguments, which leads to slow
down.
Before this PR
```
...
└─ 17.767 FxOnnxInterpreter.run  torch/onnx/_internal/fx/fx_onnx_interpreter.py:418
└─ 17.763 run_node  <@beartype(torch.onnx._internal.fx.fx_onnx_interpreter.FxOnnxInterpreter.run_node) at 0x7f7c73513e50>:1
[2 frames hidden]  <@beartype(torch.onnx._internal.fx.fx...
17.761 wrapper  torch/onnx/_internal/diagnostics/infra/decorator.py:70
├─ 15.735 format_function_signature_in_markdown  <@beartype(torch.onnx._internal.diagnostics.infra.decorator.format_funct …
```
=> TorchScriptTensor to cache torch dtype for performance | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
In ```_roll_input_wrangler```:
1. convert ```shifts``` from int to tensor 
2. convert ```dims``` from int or tensor to attributes list, so we can use loop in trace_only mode to process ```aten_roll(x, (y1, y2), (z1, z2))``` case.
=> Add op(roll) | feat(torchlib)

onnxscript/analysis.py, onnxscript/analysis_test.py, onnxscript/converter.py, onnxscript/converter_test.py
The analysis function "assigned_vars" was not handling loops. Fix this.
Should fix issue https://github.com/microsoft/onnxscript/issues/879
See also PR https://github.com/microsoft/onnxscript/pull/909
=> Handle loops in analysis of assigned vars

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
* __->__ #931
Fix aten::nonzero impl and test.
Fix aten::scalar_tensor test.
Add aten::scalar_tensor overload for sym number.
=> Fix aten::nonzero. Add aten::scalar_tensor overload for sym number

.github/workflows/main.yaml
Use the `EnricoMi/publish-unit-test-result-action@v2` action to publish test results to GitHub. Example:
=> Create action to display test results on Github | test

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Stable logcumsumexp with the subtract-max trick. I tried to use Scan unsuccessfully and it proved to be not needed. Thanks @gramalingam for his help with math & `Scan`
=> Stable logcumsumexp | feat(torchlib)

.azure-pipelines/release-dev.yml, .github/workflows/release.yaml
We will use Azure Dev Ops for compliant releases
=> Disable release triggers on Github | chore(release)

onnxscript/backend/onnx_export.py
A quick fix in the onnx to onnxscript exporter for handling invalid identifiers like "10" and "layer.1.embedding". (A proper solution will require checking for name clashes, but this will help meanwhile.)
=> Rename illegal identifiers when exporting

.github/workflows/main.yaml, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/error_reproduction.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
A tool to create reproduction instructions automatically from tests. To use, set `CREATE_REPRODUCTION_REPORT=1`. E.g.
```
CREATE_REPRODUCTION_REPORT=1 python -m pytest onnxscript/tests/function_libs/torch_lib/ops_test.py -k test_output_match_opinfo__concat_cpu_float32
```
- It will create md files with repro script under the `error_reports` folder. 
- Fixed `atleast_*` function implementations.
- Error reports will be uploaded to artifacts in CI.
- Updated test schema matching logic to consider `tensor(*)` compatible with `seq(tensor(*))`. New tests errors discovered by unskipped tests tracked in: https://github.com/microsoft/onnxscript/issues/960.
Close #564
=> Create error reproduction | test(torchlib)

onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes https://github.com/microsoft/onnxscript/issues/968
=> Remove skips in `scaled_dot_product_attention` | test(torchlib)

onnxscript/tests/function_libs/torch_lib/ops_test_data.py
* #979
* #978
* #977
* #976
* #973
* #972
* __->__ #971
=> Enable tests for `upsample_nearest2d` | test(torchlib)

onnxscript/tests/function_libs/torch_lib/error_reproduction.py
For better readability, we include a section in the error report that is the textual representation of the ONNX model. We cannot use it programmatically instead of textproto because it does not have initializers and would be invalid sometimes. Textproto is always the exact ONNX proto.
=> Include the textual model representation in error reports | test(torchlib)

pyproject.toml
`fEsX` -> `sfEX` to move failures to the bottom of the pytest error summary. I guess the order matters?
=> Reorder pytest results | test

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/error_reproduction.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
`aten::div.Tensor_mode` is implemented with two ONNX functions. When `rounding_mode` is `None`, we use `aten_div`. When it is not None, we use `aten_div_mode`. This way we don't need to handle when `rounding_mode==None` in `aten_div`.
For `float16` inputs we need to cast to float32 to preserve precision. Otherwise `-inf` sometimes becomes `inf` in the output.
- Additionally registers aliases "aten::divide", "aten::true_divide" to `aten_div`.
- Supports saving mismatches to error reports
- xfail and documents off-by-one errors with float16 (https://github.com/microsoft/onnxscript/issues/990, https://github.com/microsoft/onnxscript/issues/989)
Fixes #980
=> Implement `aten::div.Tensor_mode` | feat(torchlib)

onnxscript/irbuilder.py
The version checking logic for creating an attribute proto is not robust with ONNX 1.14.1. This fixes it in preparation for ONNX 1.14.1 release.
=> Fix attribute for ONNX 1.14.1 | fix

.github/workflows/lint.yaml
I realized the SARIF file wasn’t uploaded without always()
Use `i` to toggle comment display if needed.
=> Always upload SARIF in PR | chore

onnxscript/tests/function_libs/torch_lib/error_reproduction.py
Example output:
The output of ONNX Runtime does not match that of PyTorch when executing test
`ops_test.TestOutputConsistencyEagerCPU.test_output_match_opinfo__div_mode_floor_rounding_cpu_float16`, `sample 5` in ONNX Script `TorchLib`.
To recreate this report, use
```bash
CREATE_REPRODUCTION_REPORT=1 python -m pytest onnxscript/tests/function_libs/torch_lib/ops_test.py -k test_output_match_opinfo__div_mode_floor_rounding_cpu_float16
```
Shapes: `['Tensor<torch.Size([5, 10, 5]), dtype=torch.float16>', 'Tensor<torch.Size([5, 10, 5]), dtype=torch.float16>']`
<details><summary>Details</summary>
<p>
```python
kwargs = {'rounding_mode': 'floor'}
inputs = (tensor([[[-6.6953,  6.7070, -7.7422, -5.9688, -3.5234],
[-0.0703,  8.8828,  5.0195, -1.2656, -8.9922],
[-1.1250,  2.6641, -6.7773,  5.7227, …
```
=> Show a collapsible dropdown in mismatch error reports | test(torchlib)

onnxscript/evaluator.py, onnxscript/tests/eager_mode_test.py
* __->__ #383
In this PR
- Implement onnx reference evaluator as an eager backend
- Refactor some code in evaluator
I tested locally by replacing the ort evaluator with the reference evaluator. Most tests passed and some tests failed. I did not want to add xfails or bring the change to the torchlib tests yet. Would be good to merge as-is so that we at least have an alternative backend implemented.
Fixes #209
=> Implement onnx reference evaluator as an eager backend | evaluator

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Create `aten_div_mode_int` to handle int inputs to `aten::div.Tensor_mode`. I did not merge the implementation with the Float one because we do not want to cast e.g. float16 to float32 like we do with integers.
=> Create div variants for int inputs | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/graph_building_test.py
Support >2G model export by caching the model to disk when necessary.
Tested locally with `test_save_initializer_to_files_for_large_model`
Fixes #493
cc @wschin
=> Support >2G model export | torchlib(feat)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Current logic for slice_scatter doesn't handle the case when param start or end is out of range for [0, dim_value), while this case is valid. Most of the case (for transformer models) it will use MAX_INT for end. Current test data doesn't have such case so it doesn't cover such case. Using (torch.zeros(8, 8), torch.ones(2, 8), 0, 6, 100, 1) can fail current implementation.
This PR is to fix this, and also adjust the logic to make it simpler. The Transpose logic in current implementation is not necessary.
The new implementation passes all current test data as well as above one. I don't know how to add new test data to current UT code, someone please help me on this.
Fixes https://github.com/microsoft/onnxscript/issues/945
=> Fix slice_scatter

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Add negative axis and empty axis support to `permute`. We have to mark it as `trace_only` because we need to manipulate axis. However this should be acceptable because the result is still a single op in graph.
Fixes https://github.com/microsoft/onnxscript/issues/965
=> Fix permute for all tested inputs | fix(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py, requirements/lintrunner/requirements.txt
* __->__ #1014
* #1017
Instead of hardcoded "torch_export". PyTorch exporter will fill this field with source package info of the nn.Module call represented by this graph, and eventually enclose this field in exported local function.
=> Extend 'TorchScriptGraph' with field 'domain_name'

onnxscript/backend/onnx_backend_test.py, onnxscript/backend/onnx_export_test.py, onnxscript/converter_test.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/common/onnx_script_test_case.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py, requirements/ci/requirements-ort-nightly.txt
Bump ORT version to 1.16dev and enable tests.
- Fix a bug in TorchLibOpInfo where infos with matchers defined and `enabled_if` set to False are still applied because the flag is not checked when skipping.
- Fix aten_hstack implementation
- Explicitly supply execution providers in inference sessions as required by the new version of ORT.
=> Bump ORT version to 1.16.0.dev20230824001 and enable tests | ci(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
`include_initializer` is created and controled by fake_mode to detach initializers with their default values, preventing fake tensor becomes initializers. However, initializer could be constant tensors which should not be detached from its default value, as it's always real tensor. This PR removes the parameter, because after https://github.com/pytorch/pytorch/pull/107836, the filtering logic is added into converter.
NOTE: `include_initializers` is kept for potentially usage of debugging/experimenting on large scale models.
=> Add initializer setter to support constant tensors in fake mode export | torchlib(feat)

requirements-dev.txt
https://github.com/onnx/onnx/pull/5294 introduced a dependency to cv2 in tests, which fails our release pipeline. Instead of requiring cv2 we pin onnx to dev20230807 for now to unblock the release pipeline.
=> Pin onnx-weekly to dev20230807 in requirements-dev | fix(release)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Reference: https://github.com/pytorch/pytorch/pull/107920
=> Implement `aten::round.decimals` | feat(torchlib)

.azure-pipelines/_release-template.yml, .azure-pipelines/release.yml
Move the test steps out of the dev-release pipeline because the tests may fail due to dependency changes. For the dev pipeline we need to ensure daily releases are successful and are less worried about failing tests. The tests steps are moved to only exist in the official release pipeline.
=> Move the test steps out of the dev-release pipeline | ci(release)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/special.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Move `aten_special_softmax` -> `aten_softmax`, support alias and when dtype input is None. Implement `_softmax` using `softmax`.
An alternative would be to create a decomp in pytorch from _softmax to softmax. But since pytorch optimization tends to create decomp to private ops (and not the other way around) in different optimizations steps as @BowenBao pointed out, we still need to support _softmax here.
=> Implement `aten::_softmax` | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Use And and Or to create variants because ONNX Min/Max does not take BOOL input.
=> Implement maximum/minimum for Boolean inputs | feat(torchlib)

onnxscript/irbuilder.py
In protobuf 4.x fields aren't defined as class attribute so it should check instance attribute instead
```
>>> import google.protobuf
>>> google.protobuf.__version__
'4.21.0'
>>> import onnx
>>> hasattr(onnx.FunctionProto, "attribute_proto")
False
>>> hasattr(onnx.FunctionProto(), "attribute_proto")
True
```
=> Fix `attribute_proto` generation of function in protobuf 4.X

.azure-pipelines/_release-template.yml
Previously we publish only the wheel file and not the source distribution. Update to publish source as well by including the source in the upload
=> Publish source to PyPI as well

onnxscript/function_libs/torch_lib/ops/core.py
So far, no idea about the shape inference differ error. If we comment the check_model(), the testing will pass.
=> Fix aten_var_mean for float16 inputs

onnxscript/function_libs/torch_lib/ops/core.py
Previously `_embedding_bag` was registered to `aten_embedding_bag` when it should have been registered to `aten_embedding_bag_padding_idx` because of its signature.
=> Register `_embedding_bag` correctly | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
`_scaled_dot_product_flash_attention` is one out of three ATen implementations of `nn.functional.scaled_dot_product_attention` according to the page: https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html.
As of which one of three ATen operator is representing `nn.functional.scaled_dot_product_attention` in a model is decided by a context manager: https://pytorch.org/docs/stable/backends.html. From ONNX perspective, they have no difference except the function signature.
Only the first result matters in terms of the model prediction, and the unrelated outputs are following the below code:
```python
@register_meta(
[
aten._scaled_dot_product_flash_attention,
]
)
def meta__scaled_dot_product_flash(
query: Tensor,
key: Tensor,
value: Tensor,
dropout_p: …
```
=> Add Op(_scaled_dot_product_flash_attention) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
ONNX op 'Range' behaves differently with Torch op 'arange' when the expected output dtype is INT32.
Totally 2 differences are found in two conditions below:
1. 'start' is negative, or 
2. 'step' is negative. 
This PR will make necessary adjustments to make these 2 ops behave same.
Fix #974 .
=> Fix arange issue for int8/int16/int32 dtype

onnxscript/backend/onnx_export.py, onnxscript/backend/onnx_export_test.py
The existing exporter creates invalid python identifiers like "onnxscript.atenlib1" when generating variable names for opsets. Change this to create a name like "onnxscript_atenlib1".
=> Ensure exporter creates valid python name for opset vars

requirements/ci/requirements-ort-nightly.txt
For ORT 1.16 release verification.
=> Bump ORT-nightly to 1.16rc2 | chore(ci)

onnxscript/_internal/deprecation.py, onnxscript/values.py
Add the opname property to OnnxFunction for backward compatibility with PyTorch 2.0. Marked as deprecated.
`test.py`
```python
import onnxscript
from onnxscript.onnx_opset import opset18 as op
custom_opset = onnxscript.values.Opset(domain="torch_onnx", version=1)
#'LGamma'
@onnxscript.script(custom_opset)
def LGamma(X):
abs_gamma_x = op.Abs(X)
output = op.Log(abs_gamma_x)
return output
```
Result:
```
>>> import test
>>> test.LGamma.opname
<stdin>:1: FutureWarning: 'onnxscript.values.OnnxFunction.opname' is deprecated in version 0.1 and will be removed in 0.3. Please use '.name' instead.
'LGamma'
```
=> Add the opname property to OnnxFunction for BC | fix(api)

noxfile.py, requirements-dev.txt
Avoid 0.16.0 because of https://github.com/beartype/beartype/issues/282
=> Update beartype version | ci

onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Add one property for TorchLibOpInfo.compare_shape_only_for_output, the value is tuple(int), for example, 
```
TorchLibOpInfo(
"ops.aten.embedding_bag",
core_ops.aten_embedding_bag,
tolerance={torch.float16: (1e-2, 1e-2)},
trace_only=True,
compare_shape_only_for_output=(1,2,3),
),
```
The ```(1,2,3)``` means compare value for output[0], and compare shape for output[1],[2],[3]
=> Compare value or shape for specified outputs | test(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/special.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes https://github.com/microsoft/onnxscript/issues/1077
=> Implement _log_softmax | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Implement rand* ops. I split all ops that can take a dtype into two overloads to avoid trace_only logic.
Replaces https://github.com/microsoft/onnxscript/pull/875
=> Implement rand* ops | feat(torchilb)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Implement
- aten::normal.Tensor_Tensor
- aten::normal.float_Tensor
- aten::normal.Tensor_float
Created customized test cases for the op.
=> Implement `aten::normal` overloads | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
Previously I mistakenly swapped mean and std when transforming $X \sim N(0, 1)$ to $X \sim N(mean, std^2)$
Original PR: https://github.com/microsoft/onnxscript/pull/1094
=> Fix scale normal distributions in `aten::normal` | fix(torchlib)

onnxscript/function_libs/tools/torch_lib/deduce_type_constraints_test.py, onnxscript/function_libs/torch_lib/_constants.py, onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/ops/common.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/registration.py
This change introduces two shared operators `Rank` and `IsScalar`. They are used to replace the `Size(Shape())` pattern for code reuse and readability.
I used a hack to always include these shared functions in the model proto because without #834 we cannot dynamically add these functions to the model as they are used. I added a TODO for this.
The first usage is in `aten_all`. I will update the rest of the functions in a separate PR.
#1095
=> Create the Rank and IsScalar shared functions | feat(torchlib)

onnxscript/function_libs/tools/torch_lib/deduce_type_constraints_test.py, onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Decompose addmm with Gemm by creating a special variant for `FLOAT` and conditionally check for the ranks if the input tensors. The if branch is expected to be folded away by constant folding passes.
I have not found other instances where Gemm is used in the torch.onnx exporter.
Fixes https://github.com/microsoft/onnxscript/issues/1089
cc @baijumeswani
=> Decompose addmm with Gemm | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
When I looked at the test coverage for `addmm` (below), I realized mat1 and mat2 are always 2d tensors. So the rank check is redundant. `addmm` is now fully mapped to `Gemm`, which should completely resolve https://github.com/microsoft/onnxscript/issues/1089
Closes https://github.com/microsoft/onnxscript/issues/1110
=> Use Gemm to implement addmm | fix(torchlib)

noxfile.py
ORT -> 1.16.1 / PyTorch -> 2.1
=> Update test dependencies

onnxscript/function_libs/torch_lib/ops/core.py
Fix https://github.com/microsoft/onnxscript/issues/817
Add the support of `_native_batch_norm_legit_no_training` and `_native_batch_norm_legit`, which are two new aten ops to replace aten::native_batch_norm according to https://github.com/pytorch/pytorch/blob/a44f8894fa6d973693aab44a3dda079a168b05c1/torch/_decomp/decompositions.py#L1501-L1510.
Previous to this PR, due to lack of support of `_native_batch_norm_legit_no_training` and `_native_batch_norm_legit`, the exporter decomposes `native_batch_norm` to a bunch of other nodes and drags down the performance.
NOTE: The mismatch result size between CUDA/CPU export doesn't happen even with these nodes supported. Could be fixed somewhere else.
Tested with the code:
```python
import torch
import onnxruntime
def repro_split():
class …
```
=> Add Op(_native_batch_norm_legit_no_training and _native_batch_norm_legit) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Script embedding_renorm by correctly unpacking the outputs of `op.Unique`. Removed the trace_only function.
=> Script embedding_renorm | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/prims.py
Previously when we call e.g. `convert_element_type(a, dtype=complex64)`, we create a node with `COMPLEX64` output. This is not what we want because we always the real representation of a complex number in the ONNX graphs.
This change updates the logic to handle when the specified dtype is a complex type, in which case we add an additional axis to the end of the tensor and fill it with zeros to represent the imaginary part.
Tested locally:
```
>>> prims_convert_element_type(np.zeros(1), 14)
array([[0., 0.]], dtype=float32)
>>> prims_convert_element_type(np.zeros(1), 15)
array([[0., 0.]])
```
Fix https://github.com/microsoft/onnxscript/issues/1122
=> Handle complex types in convert_element_type | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
Previously `var_mean.dim` handles dim only when it is a tuple. It can be a list as well in practice.
=> Fix var_mean when input dim is a list | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/prims.py
Set convert_element_type to trace_only because different branches return different dtype values.
Fixes https://github.com/microsoft/onnxscript/issues/1128
=> Trace convert_element_type | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Implement einsum and fix a bug in the test code where we mistakenly treated `str` as a tensor. xfailed cases related to https://github.com/onnx/onnx/issues/5739 and when input is int32.
Fixes https://github.com/microsoft/onnxscript/issues/1130
=> Implement `einsum` | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Handle negative dimensions when transposing complex inputs.
=> Implement `transpose` for complex inputs | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
Fix https://github.com/microsoft/onnx-converters-private/issues/190
With https://github.com/pytorch/pytorch/pull/112758, this PR moves built-in function ops mapping into torchlib.
NOTE: module name of `operator.add` is _operator
=> Add Op(built-in function ops) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/linalg.py
Comparing float values `1.0` and `2.0` can be fragile. Should we do it?
Related: https://github.com/microsoft/onnxruntime/issues/18338
=> Use ReduceL1/ReduceL2 for vector norm | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fix #1140 
Add
(1) `aten::_native_batch_norm_legit.no_stats`
(2) `aten::_to_copy`
(3) `aten::_native_batch_norm_legit_functional`
`aten::_native_batch_norm_legit_functional` is only invoked by Functionalization pass, so it can't be tested in op_test. It will be added into op_test in converter side. The only difference btween the op and `aten::_native_batch_norm_legit` is the output numbers. `aten::_native_batch_norm_legit_functional` returns running_mean and running_var according to https://github.com/pytorch/pytorch/blob/1488bafb274fcc82c8aac429bad61738bc3f950e/torch/_decomp/decompositions.py#L1804-L1826
`aten_native_batch_norm_legit` is split into two sample inputs to separately feed into different ONNX variants, since they require different set of arguments.
=> Add Ops(_native_batch_norm_legit_functional) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Handle negative dimension by computing the positive dimension index. Added test cases to guard the behavior.
=> Handle negative dimension in aten_unfold | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
I forgot to annotate the functions as complex functions.
=> Annotate aten `div` and `mul` complex implementations | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/common.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/prims.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
https://github.com/pytorch/pytorch/issues/113444 Exposed an error where when `dtype=torch.complex64` in `aten_scalar_tensor_sym_number`, we produce a node with it output being complex. This change extracts the logic from `prims::convert_element_type` to a common function to handle complex dtypes.
Adds complex test for `scalar_tensor`.
=> Create shared function to handle complex casting | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
`aten::_to_copy.default` needs attributes, so this PR creates one to replace the old one.
https://github.com/pytorch/pytorch/blob/fe5d8850e27d98439166c76ccc5e167fd3960df8/aten/src/ATen/native/native_functions.yaml#L7479-L7486
https://github.com/pytorch/pytorch/pull/62262/files#diff-2f3dbd85efb9b5172f2264eedd3be47dd765e6ab7cc8bf3ade5e62c28ae35991
=> Add Op(aten::_to_copy) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
Cast the output of `aten_copy` to `self`'s type.
Fixes https://github.com/microsoft/onnxscript/issues/1162
=> Fix `aten_copy` dtype | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
Update calls to `Shape` to use the `start` and `end` arguments to simplify the graph and avoid `Gather` nodes.
=> Clean up Shape calls | chore(torchlib)

onnxscript/backend/onnx_export.py, onnxscript/backend/onnx_export_test.py, onnxscript/testing.py
Attribute parameters and normal values (like tensors) use the same namespace in onnxscript/python. This can cause a conflict when converting ONNX proto back to onnxscript (since these are different namespaces in ONNX). Examples of where this happens shown in test-case below: eg., when an attribute-parameter "yyy" is used as a value, the onnxscript translator introduces a value called "yyy" which is bound to the attribute-value "yyy".
Fix this in the exporter.
=> Handle name conflict (attribute parameter) when converting back to python

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Celu only supports float in ONNX. This change adds the variant to support more floating types by manually adding casts in the function.
=> Upcast Celu for it to support more dtypes | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
Experimental feature to store symbolic shapes produced by torch dynamo inside the exported onnx model.
There is no official ONNX spec to support nodes within FunctionProto to have value info, https://github.com/onnx/onnx/issues/5487. The names for value info are generated uniquely to be retrievable based on the call site and call stack.
=> [Experimental] Export with symbolic shapes

pyproject.toml, requirements/lintrunner/requirements.txt, setup.py
Sorry to add "complex logic in setup.py".
Though it's a development feature
closes https://github.com/microsoft/onnxscript/issues/1155
I'm specifying `url` since it's not allowed in pyproject.toml: https://github.com/pypa/packaging-problems/issues/606
=> Add more URLs to package

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
As mentioned on [#1173](https://github.com/microsoft/onnxscript/issues/1173), I'm trying to add aten::var and aten::roll (complex support) in order to export one model from PyTorch to ONNX. The model uses fft functions, which requires opset 18 and torch dynamo usage.
fixes https://github.com/microsoft/onnxscript/issues/1175 fixes https://github.com/microsoft/onnxscript/issues/1174
=> aten::var implementation and aten::roll complex support

.lintrunner.toml, README.md, docs/examples/01_plot_selu.py, docs/examples/02_plot_square_loss.py, docs/examples/03_export_lib.py, docs/examples/04_plot_eager_mode_evaluation.py, docs/examples/05_plot_model_props.py, docs/examples/06_plot_model_local_funs.py, docs/tutorial/examples/forloop.py, docs/tutorial/examples/forwhileloop.py, docs/tutorial/examples/hardmax_end_to_end.py, docs/tutorial/examples/outerscope_redef_error.py, docs/tutorial/examples/scanloop.py, onnxscript/__init__.py, onnxscript/_internal/utils.py, onnxscript/backend/onnx_export_test.py, onnxscript/evaluator.py, onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py
Remove proto2text because it is simply an alias of `onnx.printer.to_text`.
=> Remove proto2text | chore!

onnxscript/function_libs/torch_lib/ops/core.py
Follow up of #1186 to fix the dtype mismatch in Sub in the `var`/`var.correction` implementation.
=> Add castlike to var | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fix linspace for float32 and float16 inputs. Fix https://github.com/microsoft/onnxscript/issues/1190
=> Fix linspace for float inputs | fix(torchlib)

onnxscript/evaluator.py, onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Clean up isinstance checks for tuples to turn some trace_only functions into script functions. This is done by updating the tracing evaluator to turn int attributes into sequences according to the function op schema.
Remove xfails for var_mean.
Fixes https://github.com/microsoft/onnxscript/issues/1191
=> Clean up isinstance checks for tuples | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fix #1160 
Follow up #1043 It's another `scaled_dot_product_XXX_attention`
It only supports CUDA.
https://github.com/pytorch/pytorch/blob/38ae17d166a001ef6837553d1ddffa111624df27/torch/_meta_registrations.py#L5195-L5236
NOTE: This PR also enables CUDA tests.
=> Add Op(aten::_scaled_dot_product_efficient_attention) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes https://github.com/microsoft/onnxscript/issues/1210. 
For hardsigmoid, `y = max(0, min(1, alpha * x + beta))` where `alpha=1/6` and `beta=0.5` is equivalent with the pytorch definition
=> Implement hardsigmoid and hardswish | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py
In converter, pyTorch sets default value of dims as empty list.
=> Fix Op(aten::roll) | feat(torchlib)

onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Xfail the new test from pytorch-nightly
=> Xfail the replicate_negative for replication_pad2d | ci(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py
Remove check_model and shape_infer in graph building because serialization adds overhead and impacts runtime when calling to_model_proto.
=> Remove check_model and shape_infer in graph building | feat(torchlib)

noxfile.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py, requirements-dev.txt, requirements/ci/requirements-onnx-weekly.txt, requirements/ci/requirements-ort-nightly.txt
Pin `expecttest==0.1.6` because version `0.2` does not play very well with the pytorch version in CI.
=> Bump ORT nightly version to 1.17.0.dev20231218002 | chore(ci)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Previous to this PR, the graph didn't support complex dtype attributes, and dim offset of cat/stack is not considered in complex dtype.
Adds:
(1) Support complex constant (convert to real reprentation)
(2) Add cat/stack complex support
NOTE: `aten_scalar_tensor_complex` only supports complex input, and if input is real to convert to complex, `aten_scalar_tensor` is invoked instead, just like we have in tests.
=> Fully support on complex dtype | feat(graph_building)

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes https://github.com/microsoft/onnxscript/issues/1159#issuecomment-1888089502 which indeed turns out to be a problem uncovered by PyTorch CI https://github.com/pytorch/pytorch/actions/runs/7508784822/job/20445196351?pr=117314.
> Fixes `align_corner` default value. The default value from pytorch signature is `False` https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html#torch.nn.Upsample.
> That said, it shouldn't matter since `align_corner` in aten signature in `native_functions.yaml` is a required argument, so in practice this function will never be invoked w/o `align_corner`.  
Above is outdated. The case is more complicated. https://github.com/microsoft/onnxscript/pull/1254#discussion_r1453948494.
In short this PR fixes the torchlib op signature to match with aten spec, …
=> Fix upsample_bilinear to respect align_corner argument

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- Refactor upsample 2d functions to use a common set of logics
- Add additional tests (`align_corners=False`; test the `aten::upsample_bicubic2d.vec` overload)
- Fix implementation for `aten::upsample_bicubic2d` by isolating the `aten::upsample_bicubic2d.vec` overload because it has a different signature.
- xfail `align_corners=False` and when scale_w and scale_h are specified
=> Refactor and fix upsample 2d | fix(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes `nfnet` in https://github.com/microsoft/onnx-converters-private/issues/196
Two changes:
- Cast locally created `weight` and `bias` to `input` dtype.
- Upcast `input` when computing `mean` and `var`.
No idea how this was not covered by unittest. The test case seems to be there.
Minimized repro:
```python
import torch
class Module(torch.nn.Module):
def __init__(self):
super().__init__()
self.bn = torch.nn.BatchNorm2d(3, track_running_stats=False)
return torch.nn.functional.batch_norm(x, None, None, self.bn.weight, training=True)
model = Module().cuda().to(dtype=torch.float16).eval()
x = torch.randn(1, 3, 224, 224, dtype=torch.float16).cuda()
op = torch.onnx.dynamo_export(model, x)
op.save("report_bn.onnx")
op.save_diagnostics("report_bn.sarif")
import onnxruntime …
```
=> Fix fp16 aten_native_batch_norm when bias is None and training is True

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
This function works well in FullGraph mode, but failed in Eager mode. Something wrong?
=> Add op(upsample nearst1/2/3d) | feat(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
* __->__ #1276
Use `{domain}::{function_name}/{value}` instead of `{function_name_1}/{function_name_2}/.../{value}` for symbolic value_info name. There are several reasons behind this update and why a fully qualified name is not needed.
1. The symbolic shape of the value is uniquely associated with a given `TorchScriptGraph` that eventually gets serialized as `FunctionProto`. Prior to serialization it should be made generally compatible for all callsites, in case there are multiple.
2. In ONNX 1.16, FunctionProto will have its own designated value_info field. This aligns with the first point that the shape itself must be made compatible.
3. In practice, all `TorchScriptGraph` objects are exported as specialized …
=> Simplify value name in symbolic shape export

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
* __->__ #1284
- Fixes #1280, #1262. Avoid exporting as onnx::BatchNormalization with training=True.
- Fixes mismatch in unittest.
=> Add Op (instance_norm) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
aten::complex has a broadcasting behavior which is implemented here.
**NOTE:** Optimizations should consider eliminating the `Expand` node when the broadcasted shape is the same as the input shape.
Fixes https://github.com/pytorch/pytorch/issues/121100
=> Implement ATen complex and polar | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test.py, onnxscript/tests/function_libs/torch_lib/ops_test_common.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- Merged implementations for `_native_batch_norm_legit_functional`
- Fix the implementation where `momentum` was not replaced with `1-momentum` to handle the ONNX spec difference.
- Update the test decorator to support skipping by device type. Skip the tests only on cpu.
Fixes https://github.com/microsoft/onnxscript/issues/1256
=> Fix and simplify native_batch_norm | fix(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py
* __->__ #1306
_C.Value's debugName is unstable.
When duplicated names are encountered, all names involved are updated by
TorchScript naming strategy. Hence the previous name stored in value_info
can be outdated.
Fixes https://github.com/pytorch/pytorch/issues/122181, https://github.com/pytorch/pytorch/issues/122150
=> Fix graph building duplicated value names

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Reverting because this causes the dispatcher in PyTorch to choose the wrong overload.  Reverts microsoft/onnxscript#1285
=> Revert "Add support for aten:index op when index is boolean | feat(torchlib)"

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tests/function_libs/torch_lib/extra_opinfo.py, onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Continuation of #1277 by @xadupre 
The onnx implementation of index_put is different in torch script exporter
(https://github.com/pytorch/pytorch/blob/main/torch/onnx/symbolic_opset11.py#L212). The PR replaces the current implementation failing on one corner case by the one from torch script.
=> Fix implementation of index_put | fix(torchlib)

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/graph_building_test.py
* __->__ #1320
Otherwise the emitted model proto instance violates the spec definition for value_info.
=> Fix graph building to exclude input, output and initializer from value_info

.github/workflows/main.yaml
Codecov actions v4 requires CODECOV_TOKEN to be provided https://github.com/codecov/codecov-action/issues/1293
=> Update CODECOV_TOKEN to upload coverage information

onnxscript/function_libs/torch_lib/graph_building.py, onnxscript/function_libs/torch_lib/graph_building_test.py
* __->__ #1341
Previous fix didn't export subgraph value info.
=> Fix bug regression in experimental value info export

onnxscript/optimizer/__init__.py
=> Skip full model shape inference if model > 2GB | feat(optimizer)

onnxscript/ir/_core.py, onnxscript/ir/_linked_list.py, onnxscript/ir/_linked_list_test.py
Use a dictionary to map the values to the boxes in the doubly linked list implementation to
1. Remove the private pointer from Node to LinkedBox
2. Simplify membership checks
3. Ensure elements in the list are unique
Also changed:
1. The node <-> graph relationships are now managed by Graph directly and not by a property_modifier function. Meaning the user is responsible to remove nodes from other graphs before adding the same node to a new graph. This helps separate the concern of the graph from the linked list, allowing us to treat the linked list as a normal list. The list also doesn't need to handle exclusivity, meaning the same value will not be removed from the original list when being added to a new list and can appear in multiple lists, which is what we expect how lists behave.
=> Simplify linked list design with a hash table

onnxscript/ir/__init__.py, onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/_protocols.py
* __->__ #1358
1. Expose OperatorIdentifier type
2. Improve methods in the TensorType class
3. Change `def_node` and `def_index` from attributes to functions to reflect their read-only properties in `Value`
4. Add `dtype` for `Value`
5. Make `Dimension` Comparable with `int` and hashable.
6. Make inputs and outputs in Graph mutable
=> [IR] Improve api usability

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py
Implement `__eq__` and `__ne__` for Shape. Supports comparing with other shapes or iterables.
=> [IR] Implement eq for Shape

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test_data.py
1. Add fix to make the aten_index op function could handle more scenarios while the type of indices is Boolean.
2. Add more tests to cover those new scenarios.
=> Fix implementation of index with boolean indices | fix(torchlib)

.gitignore, noxfile.py, onnxscript/function_libs/torch_lib/ops/core.py, pyproject.toml
Bump required ONNX to 1.16 to always target the latest ONNX version.
Compatibility: The IR should be able to process any IR versions in ONNX. The latest version of ONNX provides this backward compatibility as well as an understanding of the latest IR version.
When ONNX updates, we can bump onnxscript version to be in sync so that we always target the latest ONNX version.
=> Bump required ONNX to 1.16

onnxscript/ir/serde.py
Avoid creating empty dictionaries for metadata_props during deserialization.
When deserializing a 350k-node model, not creating the dictionary by default should save us 84mb of memory just on the nodes, according to https://lerner.co.il/2019/05/12/python-dicts-and-memory-usage/.
350k * 240 bytes = 84 mb
=> [IR] Avoid creating empty dictionaries during deserialization

tests/function_libs/torch_lib/ops_test_data.py
values of matmul of [m, 0] and [0, n] matrices are undefined.
=> Skip test for `aten::mm` when input is sized 0

onnxscript/ir/_convenience.py, onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/_protocols.py, onnxscript/rewriter/generic_pattern.py, onnxscript/rewriter/pattern.py
A second renaming PR, hopefully more stable afterward... 
1. The consumer() naming is not as accurate as it can be, because while a `Node` is a consumer/user, a `(Node, index)` is a "use". At the same time ONNX C++ IR (https://github.com/onnx/onnx/blob/c459890aa266d74ca612f334d0f3e869dcdbb597/onnx/common/ir.h#L288) as well as torch fx (https://github.com/pytorch/pytorch/blob/ea61c9cb299b6dfebc57dc9d8821c34321d568ab/torch/fx/node.py#L226) both uses the `user` / `use` concept. FX calls it `user` because it is a Node-Node relationship. We have a Node-(Node (user), index) relationship.
=> [IR] Rename Value.consumers() to Value.uses()

onnxscript/rewriter/cast_constant_of_shape.py, onnxscript/rewriter/cast_constant_of_shape_test.py, onnxscript/rewriter/pattern.py
(Continuation of refactoring of pattern implementation)
* Remove an unused method (dead code)
* Remove unused model parameter 
* Simplify opset pattern matching to check only domain (not version)
* Fix a missing commute implementation
* Fix constant-of-shape fusion to ensure that constant is a 1D tensor, not 0D
Fixes #1447
=> Simplifying pattern implementation

onnxscript/rewriter/generic_pattern.py, onnxscript/rewriter/pattern.py, onnxscript/rewriter/pattern_test.py
Previous to this PR, if rewrite pattern includes custom domain, and it's rewriting nodes inside a function. The invalid model will be generated because of lack of registered domain.
=> Update function opset imports in rewriter

onnxscript/rewriter/pattern_test.py
From https://github.com/microsoft/onnxscript/pull/1451#discussion_r1580208670, the model string should be modified with added function domain. And now we can add checker.
=> Fix opset import test in pattern_test.py

onnxscript/rewriter/cast_constant_of_shape_test.py, onnxscript/rewriter/pattern.py
When we create new values to replace old ones, we lose some of the information associated with the old values. Propagate this information. (See https://github.com/microsoft/onnxscript/issues/1455)
=> Propagate relevant info from old values to new values

onnxscript/optimizer/__init__.py
Fix #1443 
In converter/dort, tensors retains their shape and type from PyTorch models, and it saves us some efforts to infer them all like we did in torchscript. However, when it comes to symbolic shapes, we still need ONNX shape type inference. Error is raised when the inferred shape and type are different from the carried ones. This is rare, but it happens when a corner case is revealed. For example, in #1443, PyTorch generates 2 outputs with size=0 when native_batch_norm is run with CUDA.
This PR turn off the strict mode in ONNX shape type inference to avoid crash in optimizer.
=> Turn shape type inference strict mode to false in optimizer

onnxscript/function_libs/torch_lib/graph_building/_graph_building_ir.py, onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py, onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
In torchlib, we have [device specific onnx function](https://github.com/microsoft/onnxscript/blob/8dba367fb000e3696c79b618638861b5cdf759dc/onnxscript/function_libs/torch_lib/ops/core.py#L5797-L5804), therefore, we need `TorchScriptTensor` to carry device property, so converter dispatcher can dispatch the best fitted function to the ATen op.
=> Add device to TorchScriptTensor

onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py, tests/function_libs/torch_lib/ops_test_data.py
- Skip dynamo related tests for python_version = 3.12
- Reduce tolerance for certain failing tests
- (TODO) Fix failing macos tests
=> Clean up CI testing failures

tools/ir/model_zoo_test/model_zoo_test.py
The test is created as a local script so it doesn't become a long running CI test.
=> [IR] Test IR roundtrip with model zoo

onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter_test.py
In test, adding missed provider information into ORT inference session.
=> Add provider argument to bfloat16 converter test

examples/pattern_rewriting.py, onnxscript/rewriter/generic_pattern.py, onnxscript/rewriter/pattern.py
Add `__str__` methods to pattern objects and use them in the multi-output-matcher trace output.
=> Minor cleanup for multi-output-matcher verbose trace output

onnxscript/__init__.py
Create a `DEBUG` flag for onnxscript. Users can enable it via `onnxscript.DEBUG=True`. We will use this flag to enable additional invariance checking in the IR.
1/2 of #1545
=> Create a debug flag

onnxscript/converter_test.py, onnxscript/irbuilder.py
Fix bug reported in Issue #1559 :  look at opsets imported by functions _before_ using a default.
=> Use default opset only if functions don't use opset

onnxscript/rewriter/broadcast_to_matmul.py, onnxscript/rewriter/broadcast_to_matmul_test.py
Previous to this PR, no matter input a or b is expanded, they use the same flag, and that is ambiguous to the following code.
=> Fix broadcast rule of expanding dims

onnxscript/ir/__init__.py, onnxscript/ir/passes/__init__.py, onnxscript/ir/passes/_pass_infra.py, onnxscript/ir/traversal.py, onnxscript/ir/traversal_test.py, onnxscript/optimizer/remove_unused_function.py
- Create `traversal.py` for graph traversal utilities and implemented `RecursiveGraphIterator`. Expose `traversal` to the `ir` module. Fixes https://github.com/microsoft/onnxscript/issues/1556
- Remove `NodeTransformer` because `RecursiveGraphIterator` is more flexible.
- Refactor remove_unused_function.py to use `RecursiveGraphIterator`
=> Create a recursive graph iterator and use it to refactor UnusedFunctionRemover

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py
Make tensor types hashable so that it is easy to check types in a set of accepted types during schema matching.
Test hashable properties on more classes in the IR.
=> [IR] Make tensor types hashable

onnxscript/function_libs/torch_lib/graph_building/_graph_building_ir.py, onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py, onnxscript/function_libs/torch_lib/registration.py, onnxscript/values.py, onnxscript/values_test.py
- Rename the `experimental_traceable` property to `traceable`
- Preserve function signatures for OnnxFunction and TracedFunction
Fixes https://github.com/microsoft/onnxscript/issues/401
=> Preserve function signatures for OnnxFunction; stabilize `traceable` option

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test_data.py
Reference on https://github.com/microsoft/onnxscript/pull/1255/files
Partially fixes #1533
According to https://github.com/pytorch/pytorch/blob/78a6b0c4793d93d0a9105d9c92e7b88794016e66/aten/src/ATen/native/native_functions.yaml#L12500, .vec overload is different from default overload in `upsample_trilinear`.
=> Add Op (upsample_trilinear_vec) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
aten_argmax and aten_argmin have "dim=None" as default. 
https://github.com/pytorch/pytorch/blob/2369c719d485af0787d95668947125a5605bed88/aten/src/ATen/native/native_functions.yaml#L810
Previous to "trace all traceable functions" PR, scripted function manages to handle unamtched attributes if they are None, but in traced function, this becomes errors of unrecognized arguments to the function.
=> FixOp (argmax, argmin) | feat(torchlib)

requirements-dev.txt
Pinning transformers to certain version causes conflict between this package and pytorch/benchmark: https://github.com/pytorch/benchmark/blob/10801fb0a6e1a7a3b8139bbc08c2520e334f8e9b/requirements.txt#L14, which makes torchbench docker image builder fail to build: https://dev.azure.com/onnxconverter/ONNXConverter/_build?definitionId=1.
NOTE: When we actually run the torchbench (the other pipeline), we manually install 4.37.2 back to apply all function-rewriting rules.
=> Relax transformers version in requirements-dev.txt

onnxscript/function_libs/torch_lib/ops/core.py
aten_cumsum was not traceable when the input is casted because the shape information was not propagated. Turning the implementation to use pure tracing instead.
=> Fix aten_cumsum traced mode

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py
Fix the name for `getitem` and `adaptive*` ops.
=> [torchlib] Fix names for registered functions

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/special.py, onnxscript/ir/_core.py, onnxscript/ir/serde.py, onnxscript/values.py, tests/function_libs/torch_lib/ops_test_data.py
- Correctly register some torchlib functions
- Make `aten::cat` trace only
- Capture error stacks in ir.serde for a better view of errors
- Add function support in ir.to_proto / ir.from_proto
- Fix producer display in Value repr
- Add repr to ONNXFunction
=> Miscellaneous imporovements

onnxscript/rewriter/generic_pattern.py, onnxscript/rewriter/generic_pattern_test.py
See unit test below for example of pattern not handled by matcher. Basically, match-forward needs to be done for "values" as well, in addition to, "nodes".
=> Fix multi-output pattern-matcher bug

onnxscript/rewriter/__init__.py, requirements-dev.txt
Allow rewriter input/output to be IR.
Eventually, we will keep all intermediate form in IR (switching to proto only at end).
Issue https://github.com/microsoft/onnxscript/issues/1401
=> Allow rewriter input/output to be IR

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test.py, tests/function_libs/torch_lib/ops_test_data.py
Fix more signatures in torchlib that were previously overlooked
=> [torchlib] Fix more signatures

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
Fix https://github.com/microsoft/onnxscript/issues/1665
=> [torchlib] Add torchlib operator for glu

onnxscript/function_libs/torch_lib/ops/nn.py
Depends on #1707, will add unit test after #1707 merged.
=> Add aten_hardtanh_backward function

onnxscript/function_libs/torch_lib/ops/core.py
Hello,
After upgrading onnxscript from version `0.1.0.dev20240516` to the latest version, I encountered an error while trying to export my Torch model to ONNX:
```
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten.pow.Scalar']}. 
```
Upon investigating the issue, I found that the changes made to `aten_pow` in PR #1612 are causing this problem. Reverting these changes allows the model to be exported to ONNX successfully again.
Could support for `aten::pow` be reintroduced to enable smooth exporting of models?
Thank you for your consideration.
=> Register `aten::pow.Scalar` for `aten::pow`

.github/workflows/main.yaml, noxfile.py, onnxscript/function_libs/torch_lib/_flags.py
Deprecate the torchlib IR experiment and remove tests as we are building a completely new ONNX IR builder in torch-onnx for the exporter. The experimental builder is incomplete and obsolete
=> Deprecate the torchlib IR experiment and remove tests

onnxscript/function_libs/torch_lib/ops/core.py
The backward routine need aten_prod.dim_int function.
Todo: add test case for this function.
=> Add aten_prod function

onnxscript/function_libs/torch_lib/ops/core.py
Also make `native_dropout` trace_only to simplify the function.
=> [torchlib] Update type annotation for type_as

onnxscript/rewriter/generic_pattern_test.py
The multi-output pattern does not support a useful case, where the pattern's input variables are reused elsewhere.
This PR adds a test-case illustrating the scenario. I was hoping that some changes in the in-progress PR #1636 by Xavier might fix this. But I don't think it does. Adding the test-case for now. Need to figure out how to support this.
=> Add test case for unsupported input-variable reuse in multi-output pattern matcher

README.md
#TODO Add more details about function-based rewriting once tutorial for function-based rewriting is merged
=> [docs] Update README.md for brief descriptions of optimizer and rewriter tools.

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/special.py, tests/function_libs/torch_lib/ops_test_data.py
=> [torchlib] Add missing operators (set 2)

onnxscript/_internal/ast_utils.py, onnxscript/function_libs/torch_lib/ops/__init__.py, onnxscript/function_libs/torch_lib/ops/quantized_decomposed.py, onnxscript/function_libs/torch_lib/registration.py, onnxscript/main.py, onnxscript/values.py
Initial implementations for the quantization operators defined in https://github.com/pytorch/pytorch/blob/main/torch/ao/quantization/fx/_decomposed.py. Related: https://github.com/pytorch/pytorch/issues/106748
I created a new module called `quantized_decomposed.py` to host all ops that are defined under the `quantized_decomposed` namespace seen in https://github.com/pytorch/pytorch/issues/106748. I created functions for the most common linear quantize/dequantize operators.
- Also updates `FunctionType` -> `Callable` in decorators to make them play well with type checkers
=> [torchlib] Implement quantize/dequantize operators

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/special.py
Also remove the default overload for `unsafe_split` because it does not exist.
=> [torchlib] Fix registration typo in expm1

onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py, onnxscript/function_libs/torch_lib/ops/common.py, onnxscript/function_libs/torch_lib/ops/quantized_decomposed.py, tests/function_libs/torch_lib/quantization_test.py
Fix bugs in the implementation where the dtype of the zero point is not correctly set. Tested with exporter.
=> [torchlib] Fix and improve quantization support

onnxscript/_internal/runtime_typing.py
Otherwise mypy raises
```
Error (MYPY) misc
Untyped decorator makes function "to_model_proto" untyped
To disable, use `  # type: ignore[misc]`
1001  |        )
1002  |        return onnx_function
1003  |
>>> 1004  |    @runtime_typing.checked
1005  |    def to_model_proto(
1006  |        self, opset_version: int, include_initializers: bool = True
1007  |    ) -> onnx.ModelProto:
```
=> [typing] Make the `runtime_typing.checked` always typed

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Fix more registration issues https://github.com/microsoft/onnxscript/issues/1644
=> [torchlib] Fix registrations 3/n

onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py, onnxscript/ir/serde_test.py
1. Fix type annotation for _add_attribute_to_torchscript_node and removed runtime type checking because int like inputs are not correctly recognized by beartype
2. Fix `test_tensor_proto_tensor_bfloat16` with latest onnx-weekly
3. pytorch-nightly errors will be fixed separately
=> Fix weekly CI pipeline errors

onnxscript/function_libs/torch_lib/ops/core.py
- linspace: Add additional parameters
- full: Handle when size is `[]`
=> [torchlib] Fix linspace and full

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Add std_mean, std_mean.dim. std_mean.correction
=> Add op (std_mean, std_mean.dim, std_mean.correction) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
Add group normalization with instance normalization simulation (reference on native group norm).
NOTE: This approach does not support the input shape that can't reshape to (0, num_group, -1)
=> Add Op (group_norm) | feat(torchlib)

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
Remove adaptive_avg_pool implementation because our implementation using GlobalAveragePool is incorrect. We can rely on torch decomp instead.
=> [torchlib] Remove adaptive_avg_pool implementation

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/tools/benchmark/benchmark_helpers.py, onnxscript/tools/transformers_models/__init__.py
I updated torch-onnx to handle empty `[]` inputs, so the isinstance check is not needed.
=> [torchlib] Improve aten::fill

onnxscript/function_libs/torch_lib/ops/core.py
Turn aten::diagonal as trace only and fix its logic by explicitly converting python constants to onnx constants. This was needed because the exporter logic was not handling the type conversion correctly (yet)
=> [torchlib] Fix aten::diagonal

docs/tutorial/rewriter/examples/erfgelu.py, onnxscript/optimizer/_constant_folding.py, onnxscript/rewriter/erfgelu.py, onnxscript/rewriter/generic_pattern_test.py, onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/onnxruntime/fused_matmul_rule_sets.py, onnxscript/rewriter/onnxruntime/group_normalization_merge_silu.py, onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py, onnxscript/rewriter/pattern.py, onnxscript/rewriter/pattern_test.py
As discussed previously. Use parameter names _domain, _version, and _outputs for special kwargs in onnx op builder method.
=> [DRAFT] Change parameter names of builder methods for domain, version, outputs

onnxscript/ir/_core.py
Previously the node printed was incorrect.
=> [IR] Fix error message with remove(..., safe=True)

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
softmax_cross_entropy_loss is decomposed by pytorch into `log_softmax` and `nll_loss_forward`. Since ONNX has this operator we should use it.
=> [torchlib] Implement nll_loss_forward

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Change the function signature and simplify logic to handle scalars only. Some values can be eagerly evaluated.
=> [torchlib] Fix aten::arange

onnxscript/function_libs/torch_lib/ops/core.py
Fix _log_softmax by moving the IsScalar call to the top so it can be eagerly evaluated.
Also specify the squeeze axis explicitly to improve compatibility with ORT: https://github.com/microsoft/onnxruntime/issues/21661
This should fix a runtime error in XGLMForCausalLM
=> [torchlib] Fix _log_softmax

pyproject.toml
`packaging` is used to obtain version of the package. Without it there will be an import error.
=> Add `packaging` to dependencies

onnxscript/function_libs/torch_lib/ops/prims.py
Opportunistically implement prims ops since I have seen `prims::mul` being used in a model. No tests (yet) as `aten::mul` and `prims::mul` have different signatures.
=> [torchlib] Opportunistically implement prims ops

onnxscript/ir/__init__.py, onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/_external_data.py, onnxscript/ir/_external_data_test.py, onnxscript/ir/_io.py, onnxscript/ir/traversal.py
Implement efficient save/load and handle loading external data properly in the IR.
Before this change, when a ModelProto containing external data is converted to IR, the external tensor objects will load the data from a path relative to the working directory, not the ONNX file. This is because we do not store the onnx file path and thus have no way to look for the external data file.
With the change, a `base_dir` property is added to ExternalTensor that we can set, in a separate pass when the directory is available, so the object has full information to find the data file on disk. The base_dir is not serialized to the proto to maintain a relative path in the "location" field in TensorProto.
https://github.com/microsoft/onnxscript/issues/1701, …
=> [IR] Implement save/load functions in IR and handle external data properly

onnxscript/function_libs/torch_lib/ops/nn.py
Fix #1799 
Add an extra argument: `enable_gqa` to unblock the export.
The real implementation: https://github.com/microsoft/onnxscript/issues/1802
=> Fix Op (scaled_dot_product_attention) | feat(torchlib)

onnxscript/ir/_core.py, onnxscript/ir/_display.py
1. Default the paging behavior to False so calling `.display()` on objects does not hang execution when the code is not running interactively.
2. Remove coloring in the rich console to simplify the rendering process.
=> [IR] Simplify display()

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Set aten_stack to be traced only
Remove hstack and vstack as the implementations are slow but they are decomposed in pytorch
=> [torchlib] Update stack implementations

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter.py
Remove the Input type as it is only a special case of Value, and the inputs are not guaranteed to be of type `Input` when users subclass Value and provide those as inputs to the graph.
This change removes the `Input` class and changed it to be a function to maintain backward compatibility.
=> [IR] Remove the Input type

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
Fix https://github.com/microsoft/onnxscript/issues/1819
Instead, we rely on PyTorch decomposition to use aten::addmm (Gemm) for accuracy.
=> Unregister aten_linear

onnxscript/function_libs/torch_lib/ops/nn.py
Make aten::scaled_dot_product_attention fami traceable
=> Trace Ops (aten::scaled_dot_product_attention) | feat (torchlib)

onnxscript/__init__.py, onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/serde.py
Previously the external tensors are deserialized with the base path and the relative location combined. This is in accurate because we lose information on which is the actual "location" that should be written to the proto.
With this change, I added a new `location` parameter/attribute to represent the ONNX proto relative "location", and update the `path` attribute to be computed by joining the base path with the relative location. As such users can always access the `tensor.path` attribute to get to the data file. Updated `serde` to make use of this attribute.
@shubhambhokare1 please also update the offload pass in #1796 to make use of the `path` attribute.
The first parameter of the `ExternalTensor` initializer is renamed to `location`.
=> [IR] Fix external tensor path handling

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
addmm is used a lot, and it's not traced yet. We trace it for better debugging and graph experience.
=> Trace Op (aten::addmm) | feat(torchlib)

onnxscript/_framework_apis/__init__.py, onnxscript/_framework_apis/torch_2_5.py, pyproject.toml
Create stable APIs for PyTorch 2.5 so that it does not need to use any internal ONNX Script APIs. Created APIs are
```
"check_model",
"convert_version",
"get_torchlib_ops",
"optimize",
"save_model_with_external_data",
```
In pytorch, it is expected to write:
```python
import onnxscript._framework_apis.torch_2_5
```
Fixes #1827
=> [API] Create stable APIs for PyTorch 2.5

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py
A Priority Queue + Breadth First Search (PQ+BFS) stable topological sort.
1. Parent node is be always be ahead of its child node.
2. Nodes should keep original position as possible.
This algorithm handles nested subgraphs.
Fixes https://github.com/microsoft/onnxscript/issues/1427
=> [IR] Implement topological sorting on Graph

tests/function_libs/torch_lib/extra_opinfo.py
Revert it back to the original test. We can revisit and secure the test when we have spare time.
=> Revert the test of aten::_scaled_dot_product_efficient_attention

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/_external_data.py, onnxscript/ir/_external_data_test.py
Fix failing external data tests for Windows due to file permission errors
=> [torchlib] [ci] Fix failing external data tests for Windows

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test_data.py
Implement floor_divide for int inputs. We implement it only for positive inputs (using integer division) because that is the usual intended case and is the most efficient.
Create op info for the aten op because the original op info does not produce the same input expected nor has the same behavior.
Mark traceable.
Fix https://github.com/pytorch/pytorch/issues/125753
=> [torchlib] Support int input for floor_divide

onnxscript/_framework_apis/torch_2_5.py
Enable the `_TORCH_ONNX_SAVE_EXTERNAL_DATA_WITH_IR` flag to use the new external data logic. This will
- Reduce peak memory usage
- Align external data to 64k
for the torch exporter.
=> [torch api] Enable `_TORCH_ONNX_SAVE_EXTERNAL_DATA_WITH_IR`

onnxscript/_framework_apis/torch_2_5.py
Enable optimization via environment variable
=> Enable optimization via environment variable

onnxscript/_framework_apis/torch_2_5.py
Change the check on environment variable to be at runtime. This allows benchmarking code to set the environment variable as needed before export.
=> Make environment check dynamic

onnxscript/optimizer/_constant_folding.py
A couple of bugs in the optimization for split-sequence:
* Handle the case where there is only one split-value (as the op-builder returns a single IR value instead of a list of IR values in this case).
* Use 1D constant [axis] instead of scalar axis in Squeeze op.
=> Bug fixes in split-sequence optimization

onnxscript/function_libs/torch_lib/ops/nn.py
Add a line to cast inputs to INT64 because when output_size is passed in as a list of integers, the graph builder in PyTorch exporter may fail to determine the output type. We cast it to INT64 to ensure the output
=> [torchlib] Fix upsample_output_size

onnxscript/rewriter/pattern.py, onnxscript/rewriter/pattern_test.py
I updated the pattern matcher to support matching against optional inputs. The change was accidentally pushed into the main branch (not a sub-branch as I thought) ... guess the branch protections were not good enough, changed it now.
Adding test-cases now to test it in this PR.
=> Add test cases for pattern matching against optional inputs

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/function_libs/torch_lib/ops/special.py, onnxscript/function_libs/torch_lib/tensor_typing.py
Since onnx in opset 20 or so enabled bfloat16 for most relevant ops, we are just going to include allow them in torchlib (even though it is opset18 for now) to unblock bfloat16 model export.
=> [torchlib] Include bfloat16 as part of the float types

requirements/ci/requirements-onnx-weekly.txt
To 1.18.0.dev20240930 because the previous weekly was cleaned up in pypi
=> Bump onnx-weekly in CI

onnxscript/_framework_apis/torch_2_5.py, onnxscript/_framework_apis/torch_2_6.py
- optimize is turned on. It will be controlled by an option in PyTorch
- Remove the `_TORCH_ONNX_SAVE_EXTERNAL_DATA_WITH_IR` flag
=> [API] Create stable APIs for PyTorch 2.6

onnxscript/rewriter/pattern.py
Fix inputs num mismatch for node matching. 
cc @justinchuby @gramalingam
=> Check inputs num for node matching

onnxscript/function_libs/torch_lib/ops/core.py
Previously, the bias shape of ConvTranpose was wrong since, unlike Conv, it should using the 1st dimension of weight shape and not the 0th. See described in https://github.com/microsoft/onnxscript/issues/1299
In other words,
```
if bias is None:
weight_dim_0 = op.Shape(weight, start=0, end=1)
bias_shape = op.Expand(weight_dim_0, op.Constant(value_ints=[1]))
zero = op.CastLike(0.0, input)
bias = op.Expand(zero, bias_shape)
```
should be changed to something like:
```
weight_dim_0 = op.Shape(weight, start=1, end=2) if transposed else op.Shape(weight, start=0, end=1)
```
However, I think it's more efficient to just eliminate bias altogether if it's not provided instead of filling it with zeros, since the ONNX spec allows bias to be absent.
=> [torchlib] Fix wrong bias shape of ConvTranspose

onnxscript/optimizer/__init__.py, onnxscript/optimizer/_constant_folding.py
Add input size limits for constant folding. Helps avoid excessive time in optimizer in some edge cases. (The edge cases, where we have non-trivial ops applied to large tensors, are not relevant for the exporter itself. They may be of potential interest for optimization in other settings, but that can be done by user taking explicit steps.)
Still to be done: how do we specify these values from the benchmarking code? For now, the default values will be quite useful, but experimenting with these values from the benchmarking code will need a way to control these option values.
=> Use input size limits for constant folding

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Remove rsub since it is handled by decomp, and torch doesn't have a type promotion rule for rsub so we use sub instead.
Tested with 
```python
import torch
class Model(torch.nn.Module):
return 1 - x
ep = torch.export.export(Model(), (torch.tensor(1),))
print(ep)
program = torch.onnx.export(Model(), (torch.tensor(1),), dynamo=True)
print(program)
```
=> [torchlib] Do not register rsub

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/ir/_enums.py, onnxscript/ir/_enums_test.py, onnxscript/ir/_type_casting.py, onnxscript/ir/serde.py
Support the float4e2m1 dtype from IRv11 (which is not yet released). This allows our tests to pass in the weekly-onnx CI. We use the ml_dtypes.float4_e2m1fn type for numpy conversion. Since ml_dtypes.float4_e2m1fn is only available in the latest ml_dtypes release which has dropped support for python 3.8, I used a conditional logic to build the numpy dtype mapping table.
=> [IR] Support float4e2m1

onnxscript/rewriter/no_op.py, onnxscript/rewriter/pattern.py
A couple of extensions to the rewriter, motivated by fusion optimization experimentation with SmoLLM.
* Support list of constants in match-pattern.
* One multi-output scenario is easy to handle with the single-output pattern-matcher (eg. defining a fusion rule for SkipNormalization): namely when the extra outputs are intermediate values used in the computation of the first value. Extend algorithm to handle this scenario using the efficient single-output matching-algorithm.
An example for the second point is the following pattern:
```py
def skip_norm_pattern(op, input, skip, gamma, epsilon, stash_type):
skip_sum = op.Add(input, skip)
normalized = op.SimplifiedLayerNormalization(
skip_sum,
gamma,
axis=-1,
epsilon=epsilon,
stash_type=stash_type,
_domain="com.microsoft")
return normalized, …
```
=> A couple of extensions to rewriter

onnxscript/function_libs/torch_lib/ops/core.py
Runinng SmolLM_1_7b with dynamic shapes discovered that arange.start was not dynamic anymore, since https://github.com/microsoft/onnxscript/pull/1781/files.
=> [torchlib] Fix aten::arange to support dynamic shapes

onnxscript/_internal/param_manipulation.py, onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py, onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
The firs step of https://github.com/microsoft/onnxscript/issues/1914, this is setting up onnxscript CI to test whether traced_only function has enough information to process inputs to tensors.
=> [torchlib] Use traced function param schema to process inputs

opgen/README.md, opgen/__main__.py, opgen/onnx_opset_builder.py
Previously the opgen module assumes that it is installed as a package and can be found at script import. Since we are now just running it as a standalone script, I updated to imports so that it can be run directly. Added a README.
=> Update opgen for it to be runnable

onnxscript/function_libs/torch_lib/ops/nn.py
The internal namespace was used when we wanted to register all onnx functions and had to assign a namespace to internal functions. Since they are now traced, the `internal` domain is no longer meaningful.
=> [torchlib] Remove all internal namespaces

onnxscript/optimizer/_optimizer.py, onnxscript/rewriter/collapse_slices.py, onnxscript/rewriter/collapse_slices_test.py, onnxscript/rewriter/no_op.py, onnxscript/rewriter/testing.py
Fixes https://github.com/microsoft/onnx-converters-private/issues/270
It is observed that ExportedProgram could generates aten::slice.Tensor and aten::slice_scatter.default that slice nothing:
The slices would result in redundant op.Slice ops in ONNX graph that does nothing, and op.ScatterND that basically replaces the whole input to updates, which takes a lot of time in inference.
This rule set recognizes the redundant slices by checking if the following requirements are met:
(1) starts = 0
(2) ends >= inputs[dim].shape or ends == _INT64_MAX 
(3) steps == 1
This rule set recognizes the redundant scatterND by checking if the following requirements are met:
(1) indices has the same length as the first dim of input
(2) indices is from 0 to input.shape[0]
(3)input has the same shape as …
=> [rewriter] Remove redundant op.Slice and op.ScatterND

noxfile.py, onnxscript/ir/tensor_adapters.py, onnxscript/ir/tensor_adapters_test.py, pyproject_pylint.toml
Create the new public module `ir.tensor_adapters` to implement `ir.TensorProtocol` for popular frameworks so users do not have to do that again.
Next PRs will include safetensors support.
#1499
=> [IR] Create tensor adapters

onnxscript/onnx_types.py, tests/onnx_types_test.py
- Use IR types to define onnx_types so that it is not dependent on onnx package version.
- Also add INT4 and UINT4 types.
- Make some helper functions private.
=> Use IR types to define onnx_types

onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/llama_rule_sets_test.py
ExpandIdentity may fail if x_shape is None. This change fixes it.
- Also created parameterized tests
=> [Rewriter Rules] Fix Expand-Identity rule

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py, onnxscript/rewriter/pattern.py
A few extensions motivated by ongoing transformer fusion optimizations:
Pattern matching:
* Extend pattern-matching pattern to allow specifying that extra-inputs are allowed.
Optimizations:
* Concat (x) can be replaced by Identity(x)
* Redundant cast optimization was missing in core optimizer (though present as a llama rewrite rule).
* Dropout optimizations moved into core optimizer (from rewrite rule; rewrite rule has an issue, use of attribute instead of input, and it seemed better to move it into core optimizer).
In general, for optimizations involving a single node, the core optimizer is a better place (at least, as long as they are generic, and not backend-specific) than rewrite rules. It is more efficient.
* Fix input/output size limit of constant-folding to be number of bytes. (It …
=> A couple of optimizer and rewriter extensions

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py, onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_inliner.py, onnxscript/optimizer/_remove_unused.py
Create well typed getters for the Attr class
Previously, users need to self assert the values to be the correct type. From this PR on they can do
```py
a = attr.as_int()
b = a + 1
```
etc. with a being a well typed object
=> [IR] Create getters for the Attr class

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py
Values that are both inputs and initializers of a model/graph should not be treated as constants (and cannot be used for constant-folding). Unfortunately, the single `const_value` field is class Value is used both to indicate constant-values of proper constants as well as initializer values of initializers. Ideally, the IR should provide an easy way to distinguish this at the value level (with either an extra boolean flag to indicate the value is an input-value or by using distinct fields for "initializer_value" and "const_value".
Meanwhile, this PR introduces a workaround to handle the main issue.
=> Handle input initializers correctly in constant folding

onnxscript/optimizer/_inliner.py, onnxscript/rewriter/collapse_slices.py
Fixes a couple of bugs that show up in GPT2 optimization.
=> A couple of bug fixes

onnxscript/optimizer/__init__.py, onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py, onnxscript/optimizer/_inliner.py
Extract the independent optimization/refinements from [the fusion PR](https://github.com/microsoft/onnxscript/pull/1938) as a separate PR, ready to be reviewed/merged. (The fusion work is still WIP.)
* Replace Expand by Identity when applicable (in core optimization)
* Cleanup Dropout Identity replacement in the case when Dropout has mask output
* Make repeated (redundant) call to inliner efficient
=> A couple of optimizations and refinements

onnxscript/optimizer/_inliner.py
The current implementation of using the entire call-stack to produce unique names produces very long names, which makes debugging harder. Simplify this for now. (We may need some investigation to produce more meaningful names, which is future work.)
=> Simplify name uniquification in inliner

onnxscript/rewriter/collapse_slices.py, onnxscript/rewriter/collapse_slices_test.py
The pattern did not cover the dynamic shapes case, so it leads to "'<' not supported between instances of 'int' and 'SymbolicDim'" when input is dynamic.
=> [rewriter] Fix slices pattern

onnxscript/function_libs/torch_lib/ops/core.py
=> [torchlib] Make binary comparison ops and more traceable

onnxscript/function_libs/torch_lib/ops/core.py
Fix when the rank of `dim` is not known, the conditional will pick the wrong branch because the truthiness of a value is always True.
=> [torchlib] Fix aten_mean_dim

onnxscript/_framework_apis/torch_2_6.py
Create torchlib_opset for torch 2.6. This will be used for creating the model opset import as well as in `_building` for creating constant/concat nodes etc.
=> [Stable APIs] Create torchlib_opset for torch 2.6

onnxscript/function_libs/torch_lib/ops/core.py
Otherwise exporter raises `Could not determine the dtype for the input 'inputs'.`
=> [torchlib] Fix aten_instance_norm

onnxscript/rewriter/_ir_utils.py
Extracting out some IR utilities from the ongoing fusion draft version, which are useful for debugging and use in other (constant-folding and rewriter) optimizations.
=> A couple of ir utilities

onnxscript/function_libs/torch_lib/ops/core.py
As the title said the overload is not implemented in [`aten_where`](https://github.com/microsoft/onnxscript/blob/99cf79fd4ab150e3726b36fb3e9104304e203200/onnxscript/function_libs/torch_lib/ops/core.py#L8871C1-L8874C44). It should be decomposed into `nonzero` function by pytorch. 
Now it throws error as there is not enough parameters. Minimal reproducible example:
```python
import torch
class Model(torch.nn.Module):
return torch.where(x)
torch.onnx.export(Model(), (torch.tensor([0, 1, 2, 0, 3]),), dynamo=True)
```
```
<class 'ValueError'>: Required parameter 'self' is not provided. Signature: pkg.onnxscript.torch_lib::aten_where(condition: T_condition, self: TTensor, other: TTensor) -> (TTensor) where T_condition=BOOL, TTensor=INT8 | FLOAT16 | INT16 | INT32 | UINT8 | …
```
=> [torchlib] torch.where(x) - default overload - is actually not implemented

onnxscript/backend/onnx_export.py
The tool for converting onnx model to onnxscript code has a missing parenthesis when generating external data tensor descriptor.
=> Add missing close parenthesis in conversion to script

onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/llama_rule_sets_test.py
* Extend the rewrite rule that combines two Unsqueeze into one to handle the case where the axis specified using a 0D tensor.
* Expose rewrite rules in file for use selectively.
=> Update double squeeze rewrite rule

onnxscript/backend/onnx_export.py, tools/onnx2external.py, tools/onnx2script.py
Extend onnx to script converter to suppress initializers in generated script, and replace them with randomly generated weights. This allows a compact onnxscript representation of models with large initializers, especially when we don't care about the exact weights. This is useful for generating source-based test-cases from models.
Eg., this allows us to generate test-cases such as the one [here](https://github.com/microsoft/onnxscript/blob/ca11a20625fb3b170c23798e03b4366d17d6bc1c/onnxscript/rewriter/onnxruntime/xformers/_smollm_1layer.py#L18).
=> Extend onnx to script converter

onnxscript/ir/_convenience.py, onnxscript/ir/_convenience_test.py, onnxscript/ir/tensor_adapters.py
Users can now do
```python
import torch
torch_tensor = torch.tensor([1, 2, 3])
tensor = ir.tensor(torch_tensor)
np.testing.assert_array_equal(tensor, torch_tensor.numpy())
```
=> [IR] Add torch tensor support for `ir.tensor`

onnxscript/function_libs/torch_lib/ops/core.py
Add Squeeze to aten_sym_size because the output is expected to be 0d.
=> [torchlib] Squeeze sym_size

noxfile.py, pyproject.toml, requirements-dev.txt
'TypeIs' is available from `typing_extensions` v4.10.
Close #1996
=> feat: update typing_extensions requirement

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py
Extend the optimizer to enable optimizations (such as elimination of redundant Expand/Reshape) when symbolic dimensions are present. This requires propagating symbolic shape values (tensors that carry shape information that is not completely known at compile time) through the optimizer. These optimizations also help fusion optimizations (otherwise, we need more pattern variations and more complex patterns).
Handles symbolic shape propagation through Abs, Gather, Concat and uses them in Reshape/Expand. Abs shows up in Expand translation because Torch allows -1 for "no expansion" while ONNX uses 1, but this is not necessary if the input is a symbolic shape where every value is guaranteed to be non-negative.
Also fix node-level shape-inference to refine shape by merging best info from …
=> Optimizer extensions

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
Use matmul when the input is not rank 2 to avoid decomp to addmm.
=> [torchlib] Register aten.linear and use matmul to simplify graph

onnxscript/function_libs/torch_lib/ops/nn.py
Fix https://github.com/microsoft/onnxscript/issues/2023
=> [torchlib] Use Optional in type annotations for linear

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Create separate implementations for `_operator::{truediv/floordiv}` to handle SymInts
=> [torch] Fix _operator::{truediv/floordiv}

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py
Refine the size-limit heuristics used to control constant-folding. This refinement allows some common cases to be handled automatically, such as Transpose(weight) which is typically generated by the exporter. The refinement looks at the increase in model-size that would be caused replacing a node by a constant, by accounting for inputs of the node that would be eliminated as a result of the replacement.
=> Refine constant folding size limit heuristic

.github/workflows/main.yaml
upload-artifact fails because the version is deprecated. Otherwise everything fails
=> Bump upload-artifact version in CI

onnxscript/ir/external_data.py
The user should ensure the directory exists. This is consistent with the behavior of `torch.export.save` and other python methods.
=> [IR] Remove mkdirs call in external tensor save

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
=> [torchlib] Simplify squeeze

noxfile.py, onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/fft.py, onnxscript/function_libs/torch_lib/ops/linalg.py, onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/function_libs/torch_lib/ops/prims.py, onnxscript/function_libs/torch_lib/ops/special.py, onnxscript/function_libs/torch_lib/registration.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test.py, tests/function_libs/torch_lib/ops_test_common.py, tests/function_libs/torch_lib/ops_test_data.py
Fix implementations according to https://github.com/pytorch/pytorch/pull/146224. Removed Eager Mode tests since we only care about the graph constructed. Changed all traceable ops to trace_only. Removed usage of the IsScalar function.
=> [torchlib] Fix various implementations

onnxscript/function_libs/torch_lib/ops/core.py
Simplify aten_trunc implementation according to https://github.com/onnx/onnx/issues/4588#issuecomment-2658170591
Thanks @fdwr
=> [torchlib] Simplify aten_trunc implementation

docs/conf.py, onnxscript/optimizer/__init__.py, onnxscript/tools/benchmark/benchmark_helpers.py, onnxscript/tools/transformers_models/__init__.py
The function does not seem to work inplace in all cases.
=> Fix misleading annotation in the documentation

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Fix issues reported in https://github.com/microsoft/onnxscript/pull/2050#discussion_r1963837762
=> [torchlib] Implement clamp* scalar overloads

onnxscript/function_libs/torch_lib/ops/core.py
Fix #1998 
Basically, just follow the logic from symbolic_opset9.py: https://github.com/pytorch/pytorch/blob/fdb1305ace9cd875611931983eada640ab837c4c/torch/onnx/symbolic_opset9.py#L2878.
The implementation from symbolic_opset12.py claims it fixes static shapes issue, but I see no difference because dimension, size, step are all int. I also tested https://github.com/pytorch/pytorch/blob/fdb1305ace9cd875611931983eada640ab837c4c/test/onnx/test_pytorch_onnx_onnxruntime.py#L7300 with opset9 and it still works. So we don't need to capture the loop in dynamic I think.
=> Improve Op(unfold)

onnxscript/function_libs/torch_lib/ops/core.py
Register it to aten_pow instead because exponent may not be a tensor when self is SymInt.
Fixes https://github.com/pytorch/pytorch/issues/147606
=> [torchlib] Update operator:pow implementation

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
The op was failing and not traced.
=> Fix Op(unflatten)

onnxscript/ir/_core.py
The float8_e4m3fnuz type was mistaken with float8_e4m3b11fnuz, which is a different type: https://github.com/jax-ml/ml_dtypes#float8_e4m3b11fnuz
=> [IR] Fix an error when checking for float8_e4m3fnuz type in ir.Tensor

onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/llama_rule_sets_test.py, onnxscript/rewriter/pattern.py
A recent fix to the translation of pytorch symints introduces a Squeeze=>Reshape pattern that can be optimized away. This PR introduces a rewrite-rule to do this optimization.
TODO (in a separate PR): for now, this optimization needs to be explicitly invoked. This should be done by default. (But there are several other such optimizations that need to be collected and included in the default-rule list.)
=> Squeeze Reshape Identity optimization

onnxscript/function_libs/torch_lib/ops/core.py
Fixes https://github.com/microsoft/onnxscript/issues/2084
This is required to land https://github.com/pytorch/pytorch/pull/148140 in torch.export().
cc @angelayi @@justinchuby
=> add cudnn_enable flag to aten_layer_norm

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/extra_opinfo.py
This PR introduces support for `None` indices in the `index_put` function. If an index is None, it acts as a full slice (`:`).
1. Construct index grid that contains all the indices to be updated
2. Reshapes the update values to match the computed indices.
=> [torchlib] Fix index_put: handle None cases

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
Fix https://github.com/pytorch/pytorch/issues/147896
=> Add Op (Slice - complex) | feat torchlib

onnxscript/ir/serde.py, onnxscript/ir/serde_test.py
`ir.from_proto` raises an exception for `NodeProto` input type. Here this error is fixed.
Close #2093
=> [IR] Fix deserialize_node

onnxscript/function_libs/torch_lib/ops/core.py
Fix layer norm dtype mismatch errors
Fixes https://github.com/microsoft/onnxscript/issues/2099
=> [torchlib] Fix layer norm dtype

onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py, onnxscript/ir/_io_test.py
Also removed obsolete tests in graph building. The `test_save_initializer_to_files_for_large_model` test takes a very long time (slightly less than 1min) to run.
=> [CI] Fix test errors on windows

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_remove_unused.py
Turn constant folder and dce into passes to allow them to be used as individual passes in the future.
@gramalingam
=> Turn constant folder and dce into passes

onnxscript/rewriter/ort_fusions/sdpa_test.py
Add SDPA fusion unit test case
=> Add SDPA fusion unit test case

onnxscript/ir/_io.py, onnxscript/ir/passes/_pass_infra.py, onnxscript/ir/passes/common/shape_inference.py, onnxscript/ir/passes/common/shape_inference_test.py
It handles large models by removing the initializers before sending the model to onnx shape inference.
=> [IR] Create a shape inference pass using onnx shape inference

onnxscript/tools/training_helper.py, onnxscript/tools/transformers_models/phi_test.py
https://github.com/pytorch/pytorch/pull/149745 removed the ability to provide an export option.
=> Fix DORT CI according to torch-nightly changes

onnxscript/optimizer/_optimizer.py, onnxscript/rewriter/_ir_utils.py, onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/llama_rule_sets_test.py
Enable llama_rule_sets. We might need to come up with a better name.
Follow-up issue: https://github.com/microsoft/onnxscript/issues/2128
=> [rewriter] Enable llama rule sets

onnxscript/rewriter/ort_fusions/gelu.py, onnxscript/rewriter/ort_fusions/gelu_test.py
=> Add Gelu Tanh fusion rule

onnxscript/rewriter/ort_fusions/_core.py
Cleanup ort transformer-fusions.
=> Cleanup ort transformer fusions

onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/rewriter/ort_fusions/gelu.py, onnxscript/rewriter/ort_fusions/gelu_test.py
This helps us to match the optimization pattern in https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/fusion_fastgelu.py
ref: https://github.com/microsoft/onnxscript/pull/2132#discussion_r2013039689
=> [rewriter | torchlib] respect ops order in torchscript graph

onnxscript/ir/passes/__init__.py, onnxscript/ir/passes/_pass_infra.py, onnxscript/ir/passes/common/shape_inference.py, onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_remove_unused.py, onnxscript/optimizer/_remove_unused_function.py
1. Run invariant functions `requires` and `ensures` by default at Pass `__call__` to match pytorch's pass behavior. This means the invariants cannot be too expensive because they are always checked.
2. Make PassManager a `Pass` so that it can be composed.
3. Add `changes_input` attribute to indicate if the input is changed. Turn two class attributes into properties for them to be dynamic. Combining the two attributes we can tell if a pass is destructive. For now the properties are unused but they will become useful when we want to have a better guard on pass usage etc.
4. Create `Sequential`, `InPlacePass`, `FunctionalPass` to help users create passes.
=> [IR] Improve pass infra

onnxscript/rewriter/ort_fusions/rotary_embedding.py
Rotary embedding fusion needs as_function=True.
=> Rotary embedding needs function extraction

onnxscript/rewriter/generic_pattern_test.py, onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/ort_fusions/cos_sin_cache.py, onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py, onnxscript/rewriter/ort_fusions/gqa.py, onnxscript/rewriter/ort_fusions/mha.py, onnxscript/rewriter/ort_fusions/rms_normalization.py, onnxscript/rewriter/ort_fusions/rotary_embedding.py, onnxscript/rewriter/ort_fusions/sdpa.py, onnxscript/rewriter/ort_fusions/sdpa_test.py, onnxscript/rewriter/pattern.py
- Check function returns a MatchResult object instead of bool
- This allows propagating the failure reason to the tracer to help in debugging
- #TODO Improve fail message (Reviewers feel free to suggest improvements to current failure messages)
=> Make the return type of rewrite check functions a MatchResult object

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py
We optimize `Concat (x1, x2, x3)` if one or more the concat operands has zero length along the concatenated axis-dimension.
This pattern shows up, for example, in Phi models. See [this line](https://github.com/huggingface/transformers/blob/786d9c5ed920a099573ea7b6dbf265f1aeb32fc0/src/transformers/models/phi3/modeling_phi3.py#L152) in the implementation of partial-rotary-embedding:
```py
q_embed = torch.cat([(q_rot * cos) + (rotate_half(q_rot) * sin), q_pass], dim=-1)
```
In the special case of total-rotary-embedding, the second operand `q_pass` of the concat is empty. This also interferes with the pattern-matching for GQA in the generated graph. Optimizing the redundant Concat away will help with GQA fusion as well.
Handle the edge case when all operands have zero size.
=> Optimize away zero-length concat operands

onnxscript/optimizer/_inliner.py, onnxscript/optimizer/_optimizer.py, onnxscript/rewriter/__init__.py
Use passes in optimizer and rewriter.
1. By opting into using the pass infra early, we get the benefit of getting the additional features in pass infra w/o having to pay higher refactoring cost in the future. We will be able to add more sophisticated debug utilities/snapshot capabilities etc. to the passes.
2. Since we are offering the pass infra to users, we can start validating it internally by using it here. If order altering becomes a valid use case we can expect users may need that and we can create appropriate facilities to support the usage.
=> Turn inliner into a pass and use it in rewriter & optimizer

.github/release.yml
Create auto release notes according to https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes.
=> Create auto release notes

onnxscript/optimizer/_inliner.py, onnxscript/optimizer/_legacy/_optimizer.py, onnxscript/optimizer/_optimizer.py, onnxscript/rewriter/__init__.py, onnxscript/rewriter/pattern.py
In https://github.com/microsoft/onnxscript/pull/2149 the logic for skipping rewrite when no rules are provided was removed. This PR adds the logic back and hardens input checks. Now if no rules are provided to `rewrite()`, it will only run cleanup passes.
=> Handle empty rewrite rules in rewrite function

onnxscript/main.py, onnxscript/values.py
This pull request introduces type parameterization using `TypeVar` and `ParamSpec` to enhance type safety and flexibility in the `onnxscript` module.
* [`onnxscript/main.py`](diffhunk://#diff-1f9f494aa46ce42a47c4191deb91aaded1b216b24accc43685561281507e7ca8L9-R20): Introduced `_R` and `_P` type variables, and updated the `script` decorator and `transform` function signatures to use `Callable[_P, _R]` for better type inference. [[1]](diffhunk://#diff-1f9f494aa46ce42a47c4191deb91aaded1b216b24accc43685561281507e7ca8L9-R20) [[2]](diffhunk://#diff-1f9f494aa46ce42a47c4191deb91aaded1b216b24accc43685561281507e7ca8L42-R46) [[3]](diffhunk://#diff-1f9f494aa46ce42a47c4191deb91aaded1b216b24accc43685561281507e7ca8L78-R82)
* [`onnxscript/values.py`](diffhunk://#diff-9625fb4ad20b7aa13388f751c0fde3a809f2b6c …
=> Annotate `script()` with `ParamSpec` for more accurate typing

onnxscript/function_libs/torch_lib/ops/nn.py, tests/function_libs/torch_lib/ops_test_data.py
I think this improves accuracy for gelu under float16.
=> [torchlib] Precompute the constant for gelu to avoid precision loss

onnxscript/function_libs/torch_lib/ops/core.py, onnxscript/function_libs/torch_lib/ops/nn.py, onnxscript/function_libs/torch_lib/ops/special.py
Discovered in https://github.com/onnx/onnx/issues/6886#issuecomment-2797339394, the `axes` input in calls to unsqueeze are sometimes 0d. This is incorrect according to the ONNX spec. The PR fixes the instances I could find.
=> [torchlib] Fix calls to Unsqueeze to provide correct 1d axes

onnxscript/ir/passes/common/constant_manipulation.py, onnxscript/ir/passes/common/constant_manipulation_test.py
Fix #2184 
(1) Fix the corner case when the constant is the graph output, we don't lift it.
(2) Add an option to the pass controlling lifting all constants to initializers, or only "value". (following ort pass: https://github.com/microsoft/onnxruntime/blob/d7c688e15c1dc40f57140bff08c78e01a88b19fc/onnxruntime/python/tools/transformers/onnx_model.py#L525). Default to False, where we only lift "value".
=> [Pass] Fix bugs in LiftConstantsToInitializersPass

onnxscript/_internal/ast_utils.py, onnxscript/converter.py, onnxscript/converter_test.py
This pull request includes several changes to the `onnxscript/converter.py` and `onnxscript/converter_test.py` files to improve compatibility with different Python versions and simplify the code. The most important changes include removing deprecated AST node types and updating test cases to reflect these changes.
* [`onnxscript/converter.py`](diffhunk://#diff-84b261f2b595c14d374b81d15394a92e0985ec918e4205f5c3bdfcb4ace85c77L438-L445): Removed deprecated AST node types `ast.Num`, `ast.Str`, and `ast.NameConstant` from the `_is_constant_expr` method to streamline the code and ensure compatibility with Python 3.9+ where `ast.Constant` is used instead.
* [`onnxscript/converter.py`](diffhunk://#diff-84b261f2b595c14d374b81d15394a92e0985ec918e4205f5c3bdfcb4ace85c77L583-R579): Simplified the …
=> Replace ast.NameConstant with ast.Constant and remove duplicates

onnxscript/ir/passes/common/constant_manipulation.py, onnxscript/ir/passes/common/constant_manipulation_test.py
Tensors with too few elements are usually not weights and are plenty. Lifting them will make the initializer list very noisy. I added a parameter `size_limit` to control this and defaulted it to 16.
=> [pass] Avoid lifting tensors that are too small to initializers

onnxscript/ir/passes/common/topological_sort.py, onnxscript/ir/passes/common/topological_sort_test.py
Simply expose the `sort()` api as a pass for composability.
=> [pass] Create topological sort pass

onnxscript/ir/passes/_pass_infra.py
This pull request introduces validation to ensure the in-place property of a pass is respected.
Validation of in-place property:
* [`onnxscript/ir/passes/_pass_infra.py`](diffhunk://#diff-70c7e5b3422f4daaf1611d4f76578c96e4c5894cced3d51718efa0290219f7f5R139-R152): Added checks to ensure that if a pass is declared in-place, the returned model must be the same object as the input model, and if not in-place, the returned model must be a different object. Raises `PassError` if these conditions are not met.
=> [pass] Create check to ensure in-place passes are actually inplace

docs/tutorial/rewriter/rewrite_patterns.md
Description
Added a note to the rewrite patterns tutorial clarifying that the order of rules in `pattern_rewrite_rules` matters. Some rules depend on others being applied first, so incorrect order may lead to unexpected results.
@justinchuby let me know, does this helps Or something else is needed?
Fixes #2169
=> Updated docs for rewrite-patterns

onnxscript/ir/_core.py, onnxscript/ir/passes/common/constant_manipulation.py
Always assign a `Graph` object to the node's graph.
Fix https://github.com/microsoft/onnxscript/issues/2181
=> [IR] Reconcile graph in Node

onnxscript/ir/_core.py, onnxscript/ir/_core_test.py
Implement model.graphs() as a way to retrieve the main graph and all subgraphs of it in the model.
Given
(1) how useful the method is
(2) I couldn't find an appropriate name for it in `traversal.py`
(3) Users familiar with onnxruntime optimization tools expect this method. In PyTorch a similar `modules()` method exists.
I created this method as a core method instead of an iterator in `traversal.py`.
Depends on https://github.com/microsoft/onnxscript/pull/2183
=> [IR] Implement `model.graphs()`

onnxscript/rewriter/ort_fusions/_smollm_2.py, onnxscript/rewriter/ort_fusions/cos_sin_cache.py
To apply the cos sin fusion pattern-rewrite, we need to know the maximum position id.
- If model/config has this information, use it calculate max_pos_id
- If not, calculate max_pos_id using position ids using ONNX ops
- Removes dependence of pre-setting the max_pos_id for each rewrite rule
=> Avoid using fixed value for max_pos_ids in cos_sin_cache fusion

docs/intermediate_representation/tensors.md, onnxscript/ir/tensor_adapters.py, onnxscript/ir/tensor_adapters_test.py
Bring changes from https://github.com/pytorch/pytorch/pull/151259 to correctly support bfloat16 and float8* types.
=> Update TorchTensor to use ml_dtypes

onnxscript/optimizer/_constant_folding.py
In PyTorch<=2.7, the numpy arrays for bfloat16 and float8 types have dtypes UINT16 and UINT8, which leads to incorrect constant folded graphs. This PR updates the numpy helper to cast the arrays to the correct dtypes.
Fix https://github.com/microsoft/onnxscript/issues/2187
=> Update constant fold to use correct numpy type

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_optimizer.py
=> [passes] Remove external_data_folder option from FoldConstantsPass

onnxscript/ir/passes/common/_c_api_utils.py, onnxscript/ir/passes/common/debugging.py, onnxscript/ir/passes/common/onnx_checker.py, onnxscript/ir/passes/common/onnx_checker_test.py, onnxscript/ir/passes/common/shape_inference.py, onnxscript/ir/passes/common/shape_inference_test.py
- Refactor shape_inference pass to extract logic for handling large models for onnx c-api.
- Implement an onnx checker pass leveraging the refactored logic.
=> [pass] Implement checker pass and refactor shape inference

tests/optimizer/test_models.py
Fix optimizer tests by turning on onnx shape inference. This is needed to elimininate an If node that is causing ORT to crash (https://github.com/microsoft/onnxruntime/issues/24473).
I removed the argument because shape inference is the default.
=> Fix optimizer tests

onnxscript/ir/passes/_pass_infra.py, onnxscript/ir/passes/_pass_infra_test.py
Allow pass result as pass input so users can chain calls to multiple passes more easily
Before:
```py
result = pass1(model)
result = pass(result.model)
```
Now it is also possible to do:
```py
result = pass1(model)
result = pass(result)
```
=> [IR] Allow pass result as pass input

onnxscript/ir/serde.py, onnxscript/ir/serde_test.py
Handle deserializing a graph if an output that is not produced by any nodes.
This is discovered when working on https://github.com/microsoft/onnxruntime-genai/pull/1416
=> [IR] Handle invalid output deserialization

onnxscript/ir/_convenience/_constructors.py
=> Improve `ir.node` annotations to accept None inputs

onnxscript/testing/__init__.py, tools/ir/model_zoo_test/model_zoo_test.py
Update proto comparison error message to display all differences between two protos instead of failing at the first difference.
=> Update proto comparison error message

onnxscript/ir/_core.py
Use the shape.freeze() method in the codebase
=> [IR] Use shape.freeze()

onnxscript/__init__.py, onnxscript/version_converter/__init__.py
* Added `version_converter` to the list of public modules in `onnxscript/__init__.py`, allowing it to be used as onnxscript.version_converter.
* Updated the `convert_version` function in `onnxscript/version_converter/__init__.py` to support both `ir.Model` and `onnx.ModelProto` as input types.
=> Export version_converter and support model proto

onnxscript/ir/_convenience/_constructors.py, onnxscript/ir/_convenience/_constructors_test.py
(Copilot) Fix bug in `tensor()` function to handle empty sequences and require `dtype` when value is an empty sequence.
* Add a check to ensure the sequence is non-empty before performing type checks in the `tensor()` function in `onnxscript/ir/_convenience/_constructors.py`.
* Raise a `ValueError` if `dtype` is `None` and `value` is an empty sequence in the `tensor()` function.
* Update the `tensor()` function to handle the case when a sequence is empty explicitly.
* Add a test case to check if `tensor()` raises a `ValueError` when `dtype` is `None` and `value` is an empty sequence in `onnxscript/ir/_convenience/_constructors_test.py`.
* Add a test case to check if `tensor()` handles the case when a sequence is empty explicitly.
---
For more details, open the [Copilot Workspace …
=> [IR] Fix sequence handling in tensor function

onnxscript/ir/_enums.py, onnxscript/ir/_enums_test.py
Introduce short name for dtypes as a more compact way of describing the data types in strings. Users can already access the enums by name with e.g. `ir.DataType["DOUBLE"]`.
=> [IR] Introduce short name for dtypes

onnxscript/_internal/autocast.py
In https://github.com/microsoft/onnxscript/pull/2091, the call to helper was replaced with onnx ir attribute convertion. This was not properly handling when the attribute is a subgraph and when it uses values from the parent scope, which the ir doesn't have access to. The IR thus raises warnings of it not being able to find those values.
This PR reverts the change.
=> Fix attribute handling in autocast

onnxscript/rewriter/_fusion_utils.py, onnxscript/rewriter/ort_fusions/_core.py
- debug=True, can be called for all the ort-fusion rules
- apply_shape_inference=True, can be called, if we want to apply shape_inference after each fusion rule is applied
=> Update optimize_for_ort call to allow debug and shape_inference modes

onnxscript/ir/_convenience/__init__.py, onnxscript/ir/_core.py, onnxscript/ir/serde.py
Display constant values and simplify the value repr string when fields are empty.
```py
>>> from onnxscript import ir
>>> v = ir.Value(name="v1", const_value=ir.tensor(1))
>>> v
Value(name='v1', const_value=Tensor<INT64,[]>(array(1), name=None))
>>> v = ir.Value(name="v1", const_value=ir.tensor([[1]]))
>>> v
Value(name='v1', const_value=Tensor<INT64,[1,1]>(array([[1]]), name=None))
>>> print(v)
%"v1"<?,?>{Tensor<INT64,[1,1]>(array([[1]]), name=None)}
```
Fix https://github.com/microsoft/onnxscript/issues/2073
=> [IR] Display constant tensors for Value

onnxscript/ir/passes/common/unused_removal.py, onnxscript/ir/passes/common/unused_removal_test.py, onnxscript/optimizer/__init__.py
- Remove the `remove_initialized_inputs` option in dce because the contract of the pass it that it does not modify model signature. Fixed bugs where initializers are removed. Instead, users can use https://github.com/microsoft/onnxscript/pull/2253 to remove the initialized inputs first.
- Additionally updated RemoveUnusedOpsetsPass to always retain the default opset.
=> [pass] Update DCE passes

onnxscript/ir/_core.py
The display of constant value is now more concise.
```
>>> from onnxscript import ir
>>> n = ir.node("Add", [ir.Value(name="a", const_value=ir.tensor(1)), ir.Value(name="b", const_value=ir.tensor([1]*10))], name="n0")
>>> print(n)
%"anonymous:123273301338960"<?,?> ⬅️ ::Add(%"a"{1}, %"b"{[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]})
>>> print(repr(n))
Node(name='n0', domain='', op_type='Add', inputs=(Value(name='a', const_value={Tensor<INT64,[]>(array(1), name=None)}), Value(name='b', const_value={Tensor<INT64,[10]>(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), name=None)})), attributes=OrderedDict(), overload='', outputs=(Value(name='anonymous:135329937264592', producer='n0', index=0),), version=None, doc_string=None)
```
=> Create short tensor str for nodes

onnxscript/rewriter/ort_fusions/skip_normalization.py
- Rewrite SkipLayerNorm fusions and SkipRMSNorm fusions to match format of other ort-fusion patterns.
- Added check functions for ensuring shapes are as expected.
- Moving these fusions out of PR #2221 
Fusion support patterns with:
- `Add(input, skip) -> Norm`
- `Add(input, skip) -> Add (result, bias) -> Norm`
- `Add(input, bias) -> Add (result, skip) -> Norm`
NOTE:
These fusions should support:
- Planned whisper-related optimizations
- Benchmark failures stemming from wrong bias shapes for SkipLayerNorm fusions
=> Rewrite Skip fusions with check functions

onnxscript/ir/passes/common/constant_manipulation.py, onnxscript/ir/passes/common/constant_manipulation_test.py, onnxscript/optimizer/_optimizer.py
=> [Pass] Support lifting subgraph initializers to main graph

onnxscript/ir/passes/common/constant_manipulation.py, onnxscript/ir/passes/common/constant_manipulation_test.py
Implement `RemoveInitializersFromInputsPass` and `AddInitializersToInputsPass` in `onnxscript/ir/passes/common/constant_manipulation.py`.
* **RemoveInitializersFromInputsPass**
- Add `RemoveInitializersFromInputsPass` class to find and remove graph inputs with `const_value`.
- Implement `call` method to remove inputs with `const_value` from `graph.inputs`.
- Register `RemoveInitializersFromInputsPass` in the `__all__` list.
* **AddInitializersToInputsPass**
- Add `AddInitializersToInputsPass` class to find and add initializers to the graph inputs.
- Implement `call` method to add all initializers to the graph inputs if not already present.
- Register `AddInitializersToInputsPass` in the `__all__` list.
* **Tests**
- Add test cases for `RemoveInitializersFromInputsPass` in …
=> Add add/remove initializers passes

onnxscript/rewriter/generic_pattern.py, onnxscript/rewriter/pattern.py, onnxscript/rewriter/pattern_test.py
Extends the recently introduced "Or" patterns fully (without any restrictions). The general case is handled via backtracking. The Or pattern constructor function will automatically determine whether the optimized (deterministic) matching implementation can be used or if the backtracking-based implementation should be used.
=> Add support for backtracking in pattern matcher

onnxscript/function_libs/torch_lib/ops/core.py
Fix three errors
```pytb
value = ir.tensor([np.iinfo(dtype.numpy()).min], dtype=dtype)
^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/_core/getlimits.py", line 706, in __init__
raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'b'.
```
```pytb
Traceback (most recent call last):
File "/Users/runner/work/torch-onnx-op-matrix/torch-onnx-op-matrix/op_matrix/onnx_dynamo_op_survey.py", line 54, in check_single_op
onnx.checker.check_model(onnx_model, full_check=True)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/onnx/checker.py", line 180, in check_model …
```
=> [torchlib] Fix scatter reduce on error cases

docs/ir/ir_api/core.md, onnxscript/ir/__init__.py, onnxscript/ir/passes/common/inliner_test.py, onnxscript/ir/serde.py, onnxscript/optimizer/_constant_folding_test.py, onnxscript/rewriter/no_op_test.py, onnxscript/version_converter/_version_converter_test.py
Simplify conversion of the onnx textual representation to IR.
https://github.com/microsoft/onnxscript/issues/2290
=> Add from_onnx_text function to convert ONNX text to IR model

onnxscript/ir/_core.py
Create more docstrings for node and clarify the domain normalization behavior.
=> [IR] Docs for Node

docs/api/rewriter_pattern.md, onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py, onnxscript/rewriter/pattern.py
- Replace RewriteRuleAsClass with RewriteRuleClassBase to unify rule implementations.
- Also: Use as ints() on attributes in rewrite rules
=> Unify rule implementations with classes

onnxscript/optimizer/_constant_folding.py, onnxscript/version_converter/_version_converter.py
For a reported import error issue.
=> Fix RewriterContext import error

onnxscript/rewriter/ort_fusions/cos_sin_cache.py
Fix bug causing "'numpy.ndarray' object has no attribute 'const_value'" error in benchmark. 
Of the two calls to `_compute_const_freqs`, one was passing in an ir.Value, and the other a numpy array.
=> Fix bug in handling constants in cos sin fusion

onnxscript/version_converter/__init__.py, onnxscript/version_converter/_version_converter.py, onnxscript/version_converter/_version_converter_test.py
Redo of PR https://github.com/microsoft/onnxscript/pull/2295 as discussed there.
* Ensure opset_imports is updated when version converter is applied
TODO (in a separate PR):
* Cleanup error status API (and return value)
=> Fixes to version converter

onnxscript/ir/_core.py, onnxscript/ir/_linked_list.py, onnxscript/ir/_linked_list_test.py
Introduce slice support
Close #2302
=> [IR] introduce slice support on graph

onnxscript/values.py
param_schemas is still used in many places in the code. The warning should be added only the package itself does not use it anymore. Looking at the code, the replacement is not really obvious.
=> Remove unnecessary warning

onnxscript/ir/_convenience/__init__.py, onnxscript/ir/_convenience/_constructors.py, onnxscript/ir/_core.py, onnxscript/ir/_protocols.py, onnxscript/ir/_tape.py, onnxscript/ir/external_data.py, onnxscript/ir/passes/common/inliner.py, onnxscript/ir/serde.py, onnxscript/optimizer/_constant_folding.py, onnxscript/rewriter/_pattern_ir.py, onnxscript/rewriter/_rewrite_rule.py, onnxscript/rewriter/llama_rule_sets.py, onnxscript/version_converter/_version_converter.py
We defined the class `RefAttr` in the IR to represent reference attributes in ONNX. Node attributes can be `Attr` and `RefAttr`. However, since most of the time we are working with concrete attributes, the union of types creates a typing situation where we always need to assert the types before taking the values, even if we know a `RefAttr` cannot exist (outside of a function definition). 
This additionally matches the definition of AttributeProto in ONNX.
This change merged the two classes, and instead defines a `is_ref()` method for users to check the reference attribute.
The change is BC breaking for usage like `isinstance(attr, ir.RefAttr)`. Fortunately all such usages exist in this code base and not in PyTorch, so we are safe to complete the change.
=> Remove the RefAttr class

.azure-pipelines/publish-dev.yml, .azure-pipelines/publish.yml
Update the release pipeline according to onnxruntime config. Thanks @snnn
=> Create official ESRP publishing pipelines

onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py, onnxscript/rewriter/ort_fusions/mha.py
In models generated from pytorch, masks may have shapes that are broadcastable to (B, H, S, St): eg., a 2D mask of shape (S, St) or even shape (1, 1, 1, St) in one example.
ONNX's opset23 Attention op allows masks of this shape. However, ORT's contrib ops (MHA, Attention) allow a mask of shape (1 or B, 1 or H, S, St). That is: they support broadcast only for the first two dimensions. (Even that is not supported by some earlier versions of ORT, which we don't consider here.)
So, while doing fusion for MHA, we should expand the mask to ensure it satisfies the constraints of MHA/Attention.
=> Fix handling of attention-bias in MHA fusion

.azure-pipelines/publish.yml
To use environments: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops and https://learn.microsoft.com/en-us/azure/devops/pipelines/process/environments?view=azure-devops#target-an-environment-from-a-deployment-job
=> Update publish as a deployment job

onnxscript/function_libs/torch_lib/ops/nn.py
It is possible when users call `F.linear()` directly in PyTorch.
=> [torchlib] Update linear implementation to support 1d weights

onnxscript/ir/_core_test.py, onnxscript/ir/_graph_containers.py
Implement copy() for graph inputs/outputs because torch.onnx.verification is using it for version torch 2.7.
=> [IR][fix] Implement copy() for graph inputs/outputs

onnxscript/rewriter/__init__.py, onnxscript/rewriter/fuse_batchnorm.py, onnxscript/rewriter/fuse_batchnorm_test.py
Fuses `BatchNormalization` nodes into the following nodes (`Conv`, `ConvTranspose`, `Gemm`)
(https://github.com/microsoft/onnxscript/issues/2301)
=> Rewriter: Fold Batchnorm nodes

onnxscript/ir/external_data.py, onnxscript/ir/external_data_test.py
Support converting external initializers in subgraphs.
=> [IR] Handle external initializers in subgraphs

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
When we reshape from a dynamic shape, the shape can contain zeros. This change accounts for those cases.
=> [torchlib] Set allowzero=True on Reshape where appropriate

onnxscript/rewriter/_basics.py
This pull request adds a `__repr__` method to the `MatchResult` class in `onnxscript/rewriter/_basics.py`. The new method provides a string representation of the match result, improving debugging and readability.
=> Implement `__repr__` for MatchResult

onnxscript/rewriter/ort_fusions/cos_sin_cache_test.py, onnxscript/rewriter/ort_fusions/rotary_embedding_test.py
With the latest version of pytest we get 
> onnxscript/rewriter/ort_fusions/cos_sin_cache_test.py::test_case_1 - Failed: Expected None, but test returned <onnxscript.rewriter.ort_fusions.models._rotary_embedding_models._TestCase1 object at 0x117c920d0>. Did you mean to use `assert` instead of `return`?
This is because the imported functions `test_case_1` and `test_case_2` are not really test cases but were treated as such by pytest. This PR hides them from the test module so they are not triggered.
=> Fix test names for pytest

onnxscript/_internal/autocast.py, onnxscript/converter.py, onnxscript/evaluator.py
This change should fix the type of errors like below (reported in https://github.com/pytorch/pytorch/issues/153214#issuecomment-2941500656):
```pytb
File "/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/python_message.py", line 589, in init
_ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
File "/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/python_message.py", line 478, in _ReraiseTypeErrorWithFieldName
raise exc.with_traceback(sys.exc_info()[2])
File "/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/python_message.py", line 587, in init
setattr(self, field_name, field_value)
File "/usr/local/lib/python3.12/dist-packages/google/protobuf/internal/python_message.py", line 730, in field_setter
raise TypeError(
TypeError: …
```
=> Update autocast.py to fix attribute creation error

onnxscript/rewriter/_fusion_utils.py, onnxscript/rewriter/_rewrite_rule.py, onnxscript/rewriter/llama_rule_sets.py, onnxscript/rewriter/llama_rule_sets_test.py, onnxscript/rewriter/ort_fusions/_core.py
Enable the cast-cast simplification to a single cast in a couple of cases where it is valid. This shows up in examples like SmolLM (FP16) and is needed for fusion-pattern to work.
Also: add display of replaced and replacing nodes in fusion in verbose mode.
=> Cast-cast elimination

onnxscript/rewriter/ort_fusions/_core.py, onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py
Enable fused matmul rules again, since they were commented out
=> Re-enable fused matmul rules

onnxscript/function_libs/torch_lib/ops/core.py
Issue revealed by https://github.com/microsoft/onnxscript/pull/2371, which aten.max.other is lack of matching overload. It's caused by missing type promotion. The reason is that aten::max.other (binary max) is an alias of aten::maimum.default. Thus, iwhen type promotion pass dispatches torch.max through `__torch__dispatch__`, it does not find aten::max.other (However, I am not sure how `make_fx` dispatches torch.max to aten::max.other).
The existence of aten::max.other looks like a legacy code: https://github.com/pytorch/pytorch/pull/42579.
=> [torchlib] Unregister aten::max.other

onnxscript/rewriter/ort_fusions/bias_gelu.py, onnxscript/rewriter/ort_fusions/bias_gelu_test.py
Previously the domain for Gelu in the [rules implementation](https://github.com/microsoft/onnxscript/blob/main/onnxscript/rewriter/ort_fusions/bias_gelu.py#L11) was restricted to the [contributor ops implementation](https://github.com/microsoft/onnxruntime/blob/rel-1.20.0/docs/ContribOperators.md#com.microsoft.Gelu) and does not fuse Gelu from onnx ops ([introduced with opset 20](https://onnx.ai/onnx/operators/onnx__Gelu.html#l-onnx-doc-gelu)). 
This pr introduces pattern matching + tests for both variants.
closes #2362 .
@shubhambhokare1 @justinchuby Could you please review? Any feedback is greatly appreciated.
=> fix: pattern match gelu from contrib and onnx ops🐛

onnxscript/rewriter/ort_fusions/mha.py
A couple of cleanup/fixes to MHA fusion:
* Add a pattern to handle one transpose pattern (needed for codellama)
* Simplify the handling of optional mask
=> Fixes to MHA fusion

docs/tutorial/optimizer/optimize.md, onnxscript/rewriter/__init__.py, onnxscript/rewriter/ort_fusions/_core.py
Stop decomposing gemm to matmul add by default because it is a more compact representation. Move the ort fusion rules so it keeps functioning for ort.
=> Move gemm_to_matmul_add rule to ort fusion rules

onnxscript/function_libs/torch_lib/ops/core.py
While converting a new model that I'd like to add to Transformers.js, I ran into #2309, indicating that dynamic shapes aren't currently supported for `aten_unfold`:
```
File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/onnxscript/function_libs/torch_lib/ops/core.py", line 8662, in aten_unfold
low_indices = range(0, dim_size, step)
TypeError: 'SymbolicDim' object cannot be interpreted as an integer
```
So, I dug a bit into the code and with some help from Claude, I got a version which works for my use-case (output matches exactly)! 👍
Code to reproduce (adapted from https://github.com/pytorch/pytorch/issues/112844#issuecomment-2887248559)
```py
import torch
class SpecMaker(torch.nn.Module):
return torch.ops.aten.unfold(x, -1, 512, …
```
=> Support dynamic shapes for aten_unfold

onnxscript/version_converter/__init__.py
Reported in https://github.com/onnx/onnx/issues/7037#issuecomment-2994085817, there is an error when we remove all function protos when running the version converter.
=> Fix proto handling in version converter

docs/conf.py
So that onnx ir reference can be accessed from the documentation.
=> Add sphinx inter link to onnx_ir

onnxscript/rewriter/fuse_relus_clips.py, onnxscript/rewriter/redundant_scatter_nd.py
* The recently introduced scatter-nd elimination optimization requires the `remove_nodes=False` option to be more effective (which was somehow lost in the initial implementation).
* Add a missing import statement for future annotations in the `fuse_relus_clips.py` file
=> A couple of minor fixes on rewrite rules

onnxscript/optimizer/_function_folding_test.py, onnxscript/optimizer/_optimizer.py
CSE benefits from lifting constants to initializers, and from initializer deduplication. Hence, it is better to have CSE after the other two. Furthermore, we want this to apply to all constants, including `Constant(value_int=1)` etc., so set those options for lifting constants.
=> Reorder optimization passes

onnxscript/rewriter/collapse_slices.py, onnxscript/rewriter/collapse_slices_test.py
Improve the optimization for removal of redundant slices. (It doesn't currently handle dynamic shapes.) The optimization is fairly simple, and eliminates the slice when the input and output shapes are same.
=> Improve redundant slice removal

onnxscript/function_libs/torch_lib/ops/nn.py
This PR makes onnx sdpa export match the behavior of aten sdpa when boolean mask is used.
```python
import onnxruntime as ort
import torch
class ScaledDotProductAttention(torch.nn.Module):
def forward(self, query, key, value, attn_mask):
return torch.nn.functional.scaled_dot_product_attention(query, key, value, attn_mask=attn_mask)
model = ScaledDotProductAttention()
attn_mask = torch.ones(2, 4, 8, 8).bool()  # boolean mask for attention
attn_mask[0, 0, 0, :] = False  # masking an entire row (padding token)
query = key = value = torch.randn(2, 4, 8, 16)
output = model(query, key, value, attn_mask)
torch.onnx.export(
model,
(query, key, value, attn_mask),
"scaled_dot_product_attention.onnx",
input_names=["query", "key", "value", "attn_mask"],
output_names=["output"],
opset_version=18, …
```
=> Make onnx export SDPA match aten behavior

onnxscript/rewriter/collapse_slices.py, onnxscript/rewriter/collapse_slices_test.py
This adds a reproduction of the rule introduced in f42c2bbfd31edc99a849e0381ae4992da32479de leading to an incorrect rewrite of the graph.
The original rule does not consider the step parameter, which can influence the result of a `Slice` to be the identity even when input and output shape are equivalent.
The potential fix seems to be to not apply the rule on `step != 1`, therefore the second commit adds this to the original rule implementation.
=> Add reproduction test case for incorrect slice rewrite and add potential fix

onnxscript/rewriter/ort_fusions/rms_normalization.py
In RMSNorm, there are compute_type and target_type, which we run the computation on compute_type and then convert it back to target_type after RMSNorm. 
Typical example can be found in RMSNorm class in LLMs, like in GPT-OSS: https://github.com/huggingface/transformers/blob/52c6c1bb6e27ca87c4faede34a4c2a7404c17c4d/src/transformers/models/gpt_oss/modeling_gpt_oss.py#L54
Therefore, we need to take op.Cast into pattern consideration.
=> [ort_fusuion] Support fp16 in rms_norm fusion

onnxscript/rewriter/ort_fusions/shape_optimization.py
Due to changes https://github.com/onnx/ir-py/pull/148, we cannot create an empty list attribute without specifying type because it would be ambiguous.
Fix https://github.com/microsoft/onnxscript/issues/2496
=> Correctly create empty ints for Constant in rewriter

onnxscript/rewriter/ort_fusions/gelu.py, onnxscript/rewriter/ort_fusions/gelu_test.py
Add Erf-based Gelu fusion rule
=> Add Erf-based Gelu fusion rule

onnxscript/rewriter/onnx_fusions/_rms_normalization.py
Add RMS Normalization variant to support both orders for multiplying scale and normalized value.
=> Add RMS Normalization variant

onnxscript/optimizer/_constant_folding.py, onnxscript/rewriter/onnx_fusions/_rms_normalization.py
A few improvements to symbolic dim tracking (for better fusion in Gemma3).
* Track symbolic dimension additions
* Propagate symbolic dims through Reshapes/Squeeze which show up when converting them to and from 0d or 1d tensors.
* Enables elimination of superfluous "Abs" applies to symbolic shapes (before an "Expand")
=> Improve symbolic dim tracking

onnxscript/rewriter/matmul_add_to_gemm.py
As we need to check the rank of input shapes, we need to ensure that input shapes are not None before checking their rank. Used `_ir_utils.has_rank` to handle that.
=> [Rewriter(matmul_add_to_gemm)]: check shapes

onnxscript/function_libs/torch_lib/ops/core.py
According to https://onnx.ai/onnx/operators/onnx__SplitToSequence.html#summary, `If the argument split is not specified, a default scalar value of 1 is used as the value of split`, and this is the only case when `keepdims` can be set to `0`. 
Fixes https://github.com/microsoft/onnxscript/issues/2533
=> [torchlib] Modify aten_unbind to use None for split_sizes

onnxscript/function_libs/torch_lib/ops/nn.py
See issue #2539 for a better explanation. 
I know crazy stuff right =^).
=> [torch] Fix incorrect Concat when processing dynamic paddings

tests/function_libs/torch_lib/e2e_ops_tests.py
This is a follow up of https://github.com/microsoft/onnxscript/pull/2540 to add a test described in https://github.com/microsoft/onnxscript/issues/2539.
Fix https://github.com/microsoft/onnxscript/issues/2539
=> Add test for dynamic padding

onnxscript/optimizer/_constant_folding.py, onnxscript/optimizer/_constant_folding_test.py
Split input (SymbolicTensor) could have no const_value, but with shape that gives us information of how many outputs an op.Split should return.
=> [Reland] Update SplitToSequence in constant folding

onnxscript/rewriter/__init__.py, onnxscript/rewriter/rules/common/__init__.py, onnxscript/rewriter/rules/common/_min_max_to_clip.py, onnxscript/rewriter/rules/common/_min_max_to_clip_test.py
This PR adds the following transformation:
- Min(Min(X)) -> Min(X)
- Max(Max(X)) -> Max(X)
- Min(Max(X)) -> Clip(X)
- Max(Min(X)) -> Clip(X)
=> [Rewriter]: add fusion rules for successive Min/Max patterns

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/ops_test_data.py
This PR
1. Consolidates logic for `bitwise_*` functions so that the `logical_*` functions are no longer handling bool overloads of the bitwise ops.
2. Adds support for integer inputs in the `logical_*` implementations.
Replacement of #2579.
=> [torchlib] Support integers in logical_and/or ops and update other logical ops

onnxscript/optimizer/_constant_folding.py
`_constant_folding.cast` override `output.shape` with `input.shape`, that may make a static shape to dynamic shape. Here should use `_merge_shapes` instead.
=> Merge output shape with input shape instead of override

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/extra_opinfo.py, tests/function_libs/torch_lib/ops_test_data.py
Fix aten_floor_divide for negative int inputs and large int inputs. I also combined the int and float overloads for https://github.com/microsoft/onnxscript/issues/2580
Fix #2589
=> Improve aten_floor_divide for int inputs

onnxscript/_framework_apis/torch_2_5.py
Update torch api error message to include value names when raising error on uninitialized values
=> Update torch api error message to include value names 

onnxscript/function_libs/torch_lib/ops/core.py, tests/function_libs/torch_lib/extra_opinfo.py
=> support for scalar args to aten::scatter
