microsoft/onnxscript

- .flake8
- onnxscript/backend/onnx_backend.py
- onnxscript/test/functions/onnx_script_test_case.py
- onnxscript/test/testutils.py
- onnxscript/utils.py
- onnxscript/values.py
- pyproject.toml
- requirements-dev.txt
- tools/style.bat
- tools/style.sh
Configure pydocstyle to enable flake8 test for docstring style.
> Configure pydocstyle

- onnxscript/converter.py
Fix error message in converter when a non-opset is used in place of opset.
> Fix error message

- onnxscript/backend/onnx_export.py
- onnxscript/onnx_types.py
- onnxscript/test/type_annotation_test.py
Merge the two classes TensorType and ParametricTensor into one class, and related cleanup.
> Cleanup TensorType

- onnxscript/converter.py
Remove out-dated, unused method.
> Delete unused code

- onnxscript/eager_mode_evaluator.py
- onnxscript/onnx_opset.py
> Add support for onnx-ml

- README.md
- docs/conf.py
- requirements-dev.txt
Fix CI failures caused by recent changes for fetching packages from Azure.
> Update package URL

- requirements-dev.txt
Fix for CI failure for building documentation.
> Pin sphinx version

- .github/workflows/main.yaml
- onnxscript/irbuilder.py
- onnxscript/onnx_opset.py
- onnxscript/test/eager_test.py
torch.stft changed in torch 1.13 (released on 10/28). The result is the same the dimensions are not.
Signed-off-by: xadupre <xadupre@microsoft.com>
> Fix CI jobs after torch update to 1.13

- onnxscript/converter.py
- onnxscript/test/models/signal_dft.py
Remove the explicit usage of _libcall. It's not needed.
> Remove _libcall usage

- onnxscript/tensor.py
- onnxscript/test/tensor_test.py
Implement `__index__` and `__float__` to support `range(<Tensor>)` and `float(<Tensor>)`. Also added types.
> Implement `__index__` and `__float__` on Tensor

- .github/workflows/main.yaml
- onnxscript/backend/onnx_backend.py
- onnxscript/backend/onnx_export.py
- onnxscript/converter.py
- onnxscript/debuginfo.py
- onnxscript/evaluator.py
- onnxscript/test/converter_test.py
- onnxscript/test/eager_test.py
- onnxscript/test/functions/onnx_script_test_case.py
- onnxscript/test/onnx_backend_test.py
- pyproject_pylint.toml
* #185
* __->__ #191
- Also enable pylint `consider-using-f-string` rule
> Convert more % formatted strings to f-strings

- onnxscript/converter.py
- onnxscript/test/models/identity.py
A continuation of the recent PR to handle copy-assignments. This handles such assignments inside a loop body. (Forgot to merge this change with the previous PR).
> Handle copy within loop body

- onnxscript/__init__.py
- pyproject.toml
- setup.py
- Move everything to pyproject.toml
- Simplify how version is specified
> Simplify setuptools config

- .github/workflows/main.yaml
- Replace build sdist build with https://peps.python.org/pep-0517/
> ci: use pep 517 build

- .editorconfig
- .gitignore
- .lintrunner.toml
- .vscode/extensions.json
- Remove linters that need grep
- Add editor config
> chore: linter config; add .editorconfig

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/function_libs/torch_aten/ops/nn.py
> chore(atenlib): use opset18

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/function_libs/torch_aten/ops/nn.py
> chore(atenlib): use opset18 (#239)

- .github/workflows/lint.yaml
- .github/workflows/main.yaml
- azure-pipelines.yml
- onnxscript/backend/onnx_backend.py
- onnxscript/backend/onnx_export.py
- onnxscript/irbuilder.py
- onnxscript/test/common/onnx_script_test_case.py
- onnxscript/utils.py
- pyproject.toml
- requirements-dev.txt
- requirements-onnx.txt
- Pin onnx version to 1.12; Need fixing #249 for supporting onnx 1.13
- Fix new mypy errors and adjusted mypy config
> ci: pin onnx version to 1.12; fix ci errors

- onnxscript/function_libs/torch_aten/ops/__init__.py
- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/poc/os_graph_builder.py
The graph is incorrect since alpha's default value (`1.0`) was not translated into the proto (`0` below). The graph is also overly complex and require further simplification. Should we simplify this in an optimization pass?
Aten Sub function:
> poc: Use the functionlib

- onnxscript/type_annotation.py
- onnxscript/values.py
Revert changes to values; updated list to a frozenset for faster lookup.
> fix: forward fix #267

- .github/workflows/lint.yaml
> ci: do not run lints on drafts to make reviewing easier

- .github/workflows/codeql-analysis.yml
> chore(ci): do not run codeql on draft PRs

- onnxscript/evaluator.py
- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/test/eager_mode_test.py
- onnxscript/test/function_libs/torch_aten/ops_correctness_test.py
Handle conversion of lists between onnxscript and ort.
Fixes https://github.com/microsoft/onnx-script/issues/351
> Fix conversion between onnxscript and ort representation

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
Disable the `py/import-and-import-from` error. E.g. https://github.com/microsoft/onnx-script/security/code-scanning/6491
cc @jcwchen
> chore(codeql): disable py/import-and-import-from

- onnxscript/testing.py
- onnxscript/tests/common/testutils.py
Create a `testing` module to facilitate graph validation. Move the contents from checker and testutils to `testing`
> feat(testing): expose the graph isomorphism testing utils

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Also remove `_arange_input_wrangler` because it is not needed after #355 
Co-authored-by: @fatcat-z
Replace #333
> feat(atenlib): conv2d

- onnxscript/function_libs/torch_aten/ops/nn.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
due to string-eq not supported yet
> feat(atenlib): split op(gelu) into 2 functions

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Shape in reshape was mistaken to floats
> fix(atenlib): make shape ints

- .lintrunner.toml
- requirements-dev.txt
"40% faster." https://mypy-lang.blogspot.com/2023/02/mypy-10-released.html
> chore(lint): use mypy 1.0.0

- onnxscript/function_libs/torch_aten/graph_building.py
> fix(atenlib): compact _add_constant_to_graph

- onnxscript/function_libs/tools/torch_aten/generate_aten_signatures.py
- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/function_libs/torch_aten/ops/fft.py
- onnxscript/function_libs/torch_aten/ops/linalg.py
- onnxscript/function_libs/torch_aten/ops/nested.py
- onnxscript/function_libs/torch_aten/ops/nn.py
- onnxscript/function_libs/torch_aten/ops/sparse.py
- onnxscript/function_libs/torch_aten/ops/special.py
So they show up as doc and in the onnx model.
> chore(atenlib): convert aten signatures from comments to docstrings

- noxfile.py
> chore(ci): use onnx-weekly from pypi

- onnxscript/backend/onnx_export_test.py
> fix(test): racing condition in onnx_export_test

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Due to using if-else in the function but return different type.
> feat(atenlib): modify ops(new_empty, new_empty_strided)

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Reverts microsoft/onnx-script#460
> Revert "feat(atenlib): add ops(squeeze)"

- onnxscript/function_libs/torch_aten/ops/core.py
Better comment on Expand node adjustment.
More detail can be found: https://github.com/pytorch/pytorch/pull/34069
> better comment on expand node

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
https://github.com/onnx/onnx/issues/2683
> feat(atenlib): op(cross)

- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Removed the class level parameterization
> chore(test): refactor atenlib test to make parameterization clearer

- onnxscript/function_libs/torch_aten/ops/core.py
I had to add these every time I made graph-level change...
> Add type promotion on certain nodes to enable bloom

- onnxscript/function_libs/torch_aten/graph_building.py
The bug is caught in PyTorch CI tests
> fix empty list of input handling

- onnxscript/backend/onnx_backend.py
Remove deprecated import (object) from numpy
> chore: clean up onnx_backend

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
ORT failed on FullGraph test mode, because if-else branch have different shape (rank 0 vs. rank N)
> feat(atenlib):add ops(scatter-add, floor)

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/function_libs/torch_aten/ops/nn.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Fixes #547 
Thanks @kunal-vaishnavi for helping me debug
What I learned:
1. We need SwapAxes
2. Being able to print in functions is absolutely saving time
> feat(atenlib): scaled_dot_product_attention; trilu

- onnxscript/py.typed
> Make onnx-script PEP561 compliant

- docs/examples/02_plot_square_loss.py
- docs/examples/04_plot_eager_mode_evaluation.py
- onnxscript/backend/onnx_export.py
- onnxscript/backend/onnx_export_test.py
- onnxscript/converter.py
- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/irbuilder.py
- onnxscript/main.py
- onnxscript/onnx_types.py
- onnxscript/utils.py
- onnxscript/values.py
> Rename onnx-script -> onnxscript | chore(release)

- onnxscript/function_libs/torch_aten/ops/core.py
> Improve unflatten | feat(atenlib)

- onnxscript/function_libs/torch_aten/ops/core.py
> Change SliceScatter (dim) signature | fix(atenlib)

- onnxscript/function_libs/torch_aten/ops/core.py
- onnxscript/tests/function_libs/torch_aten/ops_correctness_test.py
Added return mean,var. Actually the var should be named rstd.
```
rstd = 1 / sqrt(var+eps)
```
> modify op(native batch norm) | feat(atenlib)

- noxfile.py
Fixes the function-experiments CI.
> Update noxfile.py to reflect the new ops_test path | test(torchlib)

- .github/workflows/lint.yaml
- .lintrunner.toml
- README.md
- onnxscript/autocast.py
- onnxscript/backend/onnx_backend.py
- onnxscript/function_libs/torch_lib/graph_building.py
- onnxscript/function_libs/torch_lib/registration.py
- onnxscript/values.py
Don't timeout please (update: 2m 54s, nice)
Fixes #527
> Re-enable mypy | chore(ci)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
1. split aten_any() to aten_any_dim()
2. remove trace_only=True
3. remove xfail
> RefineOp(any) | feat(atenlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Remove xfail by refactor the implementation.
> RefineOp(index_select) | feat(atenlib)

- onnxscript/function_libs/torch_lib/ops/nn.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
1. Change if/elif to if-if
2. Remove xfail
> RefineOp(mse_loss) | feat(atenlib)

- onnxscript/function_libs/torch_lib/registration.py
- onnxscript/tests/function_libs/torch_lib/ops_test_common.py
Update to `pkg.onnxscript.torch_lib`
> Update the domain for torch_lib functions | chore(torchlib)

- onnxscript/function_libs/torch_lib/graph_building.py
- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_common.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- requirements/ci/requirements-pytorch-nightly.txt
Adapt onnx-script to complex dtype.
The main work seems to be in converter side.
~~This is the first draft for discussion.~~
> Support complex | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
Add made up aten::getitem to include special case of operator.getitem in torch.
> Add Op (getitem) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Revolves https://github.com/microsoft/onnxscript/issues/703
> Add op(mean) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/nn.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
> RefineOpForFP16(4)

- onnxscript/function_libs/torch_lib/graph_building.py
- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
* __->__ #759
* #758
Fixes #756
> Fix 'aten.gather' input order | fix(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/function_libs/torch_lib/ops/special.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
moved erf from core to special because it is an alias 
Fixes #822
> Add ops (erf*) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/README.md
- onnxscript/tests/function_libs/torch_lib/ops_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
I realized we can use Einsum for transposing matrices. So here it is.
> Add ops (mT, mH, conj, concat) | feat(torchlib)

- README.md
Remove outdated reference from README
> Remove reference to experimental branch

- onnxscript/function_libs/torch_lib/ops/core.py
Since we have type promotion now in torch
> Remove castlike in aten_add | chore(torchlib)

- onnxscript/converter.py
- onnxscript/converter_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- onnxscript/type_annotation.py
Ensure that promotion of a bool attribute parameter to a tensor creates a boolean tensor.
Fixes https://github.com/microsoft/onnxscript/issues/872
> Fix promotion of bool attribute references to tensor

- onnxscript/_internal/ast_utils.py
- onnxscript/analysis.py
- onnxscript/converter.py
- onnxscript/irbuilder.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
> Improve annotations in converter

- .github/workflows/release.yaml
* __->__ #935
More frequent releases to allow downstream use.
> Run onnxscript-preview release workflow daily | chore(release)

- pyproject.toml
1. Fix the project link
2. onnxscript is license under MIT, not Apache.
> Update package metadata | chore(release)

- .azure-pipelines/release-dev.yml
- .azure-pipelines/release.yml
I created two pipelines. They should be triggered by the individual github workflows as a second step.
> Create publish pipelines in Azure | chore(release)

- .azure-pipelines/release-dev.yml
- .azure-pipelines/release.yml
AzurePipelines now failed because of:
```
/.azure-pipelines/release-dev.yml (Line: 10, Col: 5): Unexpected value 'displayName'
334722
```
> Fix syntax error in AzurePipelines: move displayName

- .azure-pipelines/_release-template.yml
- .azure-pipelines/release-dev.yml
- .azure-pipelines/release.yml
Extracted the common steps to a template
> Create templates for Azure Pipeline reuse | chore(release)

- pyproject.toml
https://github.com/microsoft/onnxscript/issues/934
> Hide xfailed tests in test results | test(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/extra_opinfo.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
* __->__ #982
Fixes https://github.com/microsoft/onnxscript/issues/981
> Fix 'aten_unfold'

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes the new test error caused by torch-nightly
> Create aten_normal_float_float | feat(torchlib)

- README.md
- docs/tutorial/examples/hardmax_end_to_end.py
> Fix typo mpdel --> model

- onnxscript/function_libs/torch_lib/ops/core.py
Previously I omitted `complex=True`
> Register `view_as_real` as complex functions | fix(torchlib)

- .azure-pipelines/_release-template.yml
Remove the onnxscript-preview rename step.
> Publish to onnxscript | chore(release)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/function_libs/torch_lib/ops/nn.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Fixes for comparison ops, mish, bitwise_shift from findings in https://github.com/justinchuby/torch-onnx-op-matrix/pull/20
> Miscellaneous fixes of ops | fix(torchlib)

- README.md
> Create status badges in README

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
> AddOp(diagonal) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
Replace if with where for performance.
> Remove if branches in arange | fix(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
From the review comment: https://github.com/microsoft/onnxscript/pull/1116#discussion_r1380717438.
> Fix Op(_native_batch_norm_legit_no_training) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Discovered through https://github.com/pytorch/pytorch/issues/113067
> Implement squeeze.dim for complex inputs | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
Implement support for complex inputs for `+`, `-`, `*`, `/`.
Updated aten_abs to use Slice instead of Gather for runtime performance.
> Complex support for basic arithmetic | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
Fix https://github.com/microsoft/onnxscript/issues/1161
> Fix _aten_native_group_norm_onnx dtype | fix(torchlib)

- onnxscript/function_libs/torch_lib/ops/fft.py
- onnxscript/tests/function_libs/torch_lib/extra_opinfo.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- tools/onnx2script.py
Update test for _fft_r2c op and fixed its implementation.
> Create tests for _fft_r2c | test(torchlib)

- onnxscript/function_libs/torch_lib/ops/nn.py
- onnxscript/tests/function_libs/torch_lib/extra_opinfo.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- A large change in extra_opinfo.py, is just because re-sort the functions by name.
> AddOp(aten_replication_pad1d) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/nn.py
> Fix Op(aten::_scaled_dot_product_efficient_attention) under fp16

- onnxscript/function_libs/torch_lib/ops/core.py
dim1 and dim2 could go negative.
> Fix Op(aten::diagonal) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/nn.py
Fixes nanogpt from https://github.com/microsoft/onnx-converters-private/issues/196
Cont of #1204
Minimal repro
```python
import torch
class SubModule(torch.nn.Module):
return torch.ops.aten.scaled_dot_product_attention(x, x, x, is_causal=True)
class Module(torch.nn.Module):
def __init__(self):
super().__init__()
self.sub = SubModule()
return self.sub(x)
func = Module().cuda().to(dtype=torch.float16).eval()
x = torch.randn(1, 1, 1, 32, dtype=torch.float16).cuda()
op = torch.onnx.dynamo_export(func, x)
op.save("attn.onnx")
op.save_diagnostics("attn.sarif")
import onnxruntime
sess = onnxruntime.InferenceSession("attn.onnx", providers=["CUDAExecutionProvider"])
sess.run(None, {"l_x_": x.cpu().numpy()})
```
> Fix Op(aten::scaled_dot_product_attention) under fp16

- onnxscript/values.py
> Use correct logger in values.py

- onnxscript/function_libs/torch_lib/ops/core.py
> Fix Op(aten::roll) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/special.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
> Implement operator sinc | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/special.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
https://github.com/microsoft/onnxscript/issues/1223 but it is still numerically unstable.
> Fix the erfcx implementation | fix(torchlib)

- noxfile.py
- onnxscript/function_libs/torch_lib/ops/__init__.py
- onnxscript/function_libs/torch_lib/ops/vision.py
- onnxscript/tests/function_libs/torch_lib/extra_opinfo.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- requirements/ci/requirements-pytorch-nightly.txt
- Create the scaffold and tests to support torchvision ops.
- Implement `torchvision::nms`
> Implement torchvision operator `nms` | feat(torchlib)

- onnxscript/function_libs/torch_lib/graph_building.py
Reverts microsoft/onnxscript#1272
> Revert "Correctly construct nested function opset_imports for TorchScriptGraph serialization"

- onnxscript/function_libs/torch_lib/graph_building.py
* __->__ #1278
Last merge was incorrect since PR was submitted by ghstack.
https://github.com/microsoft/onnxscript/pull/1276
> Reland 'Simplify value name in symbolic shape export'

- onnxscript/function_libs/torch_lib/graph_building.py
I mistakenly copied the logic for `IsScalar` to `Rank`. `Rank` needs its own logic.
> Fix eager evaluation of the `Rank` op | fix(torchlib)

- docs/examples/01_plot_selu.py
- onnxscript/__init__.py
- onnxscript/_internal/analysis.py
- onnxscript/backend/onnx_backend.py
- onnxscript/converter_test.py
- onnxscript/diagnostics/infra/context.py
- onnxscript/diagnostics/infra/decorator.py
- onnxscript/evaluator.py
- onnxscript/evaluator_test.py
- onnxscript/function_libs/tools/torch_lib/deduce_type_constraints.py
- onnxscript/function_libs/tools/torch_lib/generate_aten_signatures.py
- onnxscript/function_libs/tools/torch_lib/generate_prims_signatures.py
- onnxscript/function_libs/torch_lib/graph_building.py
- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/irbuilder.py
- onnxscript/testing.py
- onnxscript/tests/function_libs/torch_lib/ops_test.py
- onnxscript/tests/function_libs/torch_lib/ops_test_common.py
- onnxscript/tests/function_libs/torch_lib/ops_test_data.py
- onnxscript/values.py
- opgen/__main__.py
- pyproject.toml
Enable additional ruff rules including pylint rules and others to guard code quality.
> Enable additional ruff rules

- onnxscript/function_libs/torch_lib/ops/core.py
This is linked to this issue:
https://github.com/pytorch/pytorch/issues/124160
> Implement `aten::diagonal_copy` | feat(torchlib)

- onnxscript/ir/_core.py
- onnxscript/ir/_core_test.py
- onnxscript/ir/_protocols.py
- onnxscript/ir/serde.py
`def_node()` -> `producer()`
`def_index()` -> `index()`
`users()` -> `consumers()`
Fixes https://github.com/microsoft/onnxscript/issues/1379
> [IR] Rename apis

- .github/workflows/main.yaml
- .gitignore
- noxfile.py
- onnxscript/ir/_core.py
- requirements-dev.txt
- tests/ir/serde_test.py
Reverts microsoft/onnxscript#1393
> Revert "Revert "[IR] Improve repr and test; profile serde tests; test with py312""

- onnxscript/ir/_core.py
- onnxscript/ir/_protocols.py
- onnxscript/ir/serde.py
Deserialize metadata_props. Previously they were omitted.
> [IR] Include metadata props in deserialization

- onnxscript/ir/_convenience.py
- onnxscript/ir/_core.py
- onnxscript/ir/serde.py
- onnxscript/rewriter/_tape.py
Implement `convert_attribute` and `convert_attributes` as convenience functions for the IR.
Also updates repr for Attr to make it more succinct.
> [IR] Implement `convert_attributes`

- onnxscript/ir/README.md
- onnxscript/ir/_linked_list.py
Initial readme for the IR. Describes the file structure.
> [IR] Create readme

- onnxscript/ir/README.md
Add a bullet point in the features around protobuf.
> [IR] Update README.md

- docs/index.md
- docs/tutorial/rewriter/examples/broadcast_matmul.py
- Add ONNX Script installation instructions
- Add link to Github Repo and PyPi package
> [docs] Extend landing page with installation instructions

- onnxscript/ir/_core.py
- onnxscript/ir/_core_test.py
- `node()` to get node by index or name
- `num_nodes()` to obtain the node counts
> [IR] Implement `node` and `num_nodes` on Graph

- pyproject.toml
> [build] Make the urls field dynamic

- onnxscript/ir/_core.py
- onnxscript/ir/_core_test.py
- onnxscript/ir/_name_authority.py
- onnxscript/ir/_name_authority_test.py
- onnxscript/ir/serde.py
- onnxscript/ir/serde_test.py
- onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter.py
- Store all names from the graph for generating unique names for new values.
- Also allow values to be initialized with no arguments.
Fix #1535
> [IR] Improve name authority to generate unique names

- onnxscript/rewriter/_ir_utils.py
- onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
- onnxscript/rewriter/onnxruntime/transformers/layernorm.py
- onnxscript/rewriter/onnxruntime/transformers/multihead_attention.py
- onnxscript/rewriter/pattern.py
- onnxscript/rewriter/pattern_test.py
Fix #1550 
NOTE: from https://github.com/microsoft/onnxscript/pull/1553#discussion_r1604205079, I think we can hide the None check in this function.
> Simplify get_numpy_from_ir_value

- onnxscript/function_libs/torch_lib/ops/nn.py
Fix _aten_scaled_dot_product_efficient_attention_fillin_empty_outputs regression
> Remove traceable from `_aten_scaled_dot_product_efficient_attention_fillin_empty_outputs`

- onnxscript/optimizer/remove_unused.py
- onnxscript/optimizer/remove_unused_test.py
Addresses Issue https://github.com/microsoft/onnxscript/issues/1338
> Update handling of batch-norm in DCE optimization

- docs/intermediate_representation/getting_started.ipynb
Fixes https://github.com/microsoft/onnxscript/issues/1600 by using a relative path. Validated with sphinx.
> [docs] Fix model path in IR getting started

- requirements-dev.txt
Closes https://github.com/microsoft/onnxscript/issues/1619
> Add missing `torchvision` library in requirements-dev.txt

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/function_libs/torch_lib/ops/nn.py
- tests/function_libs/torch_lib/ops_test_data.py
> [torchlib] Implement silu and fix ones_like

- onnxscript/ir/_convenience.py
cc @gramalingam . I realized we also cannot maintain the mapping in the IR, because we don’t require values to always have a name while in IR.
> [IR] Create a convenience function to create name->value mappings

- onnxscript/function_libs/torch_lib/ops/core.py
The backward routine need le.Scalar function.
> Add le.Scalar decorator to aten_le() function

- tools/optimize.py
Usage:
```
python optimize.py model.onnx optimized_model.onnx
```
> Create a executable utility to call optimizer

- onnxscript/backend/onnx_export_test.py
- onnxscript/function_libs/torch_lib/ops/quantized_decomposed.py
That fixes the dort unit test series.
> Fix none value for out_dtype in quantized_decomposed_dequantize_per_tensor

- onnxscript/function_libs/torch_lib/ops/core.py
They are one operator simple functions.
> [torchlib] Mark trig ops as traceable

- onnxscript/function_libs/torch_lib/ops/core.py
> [torchlib] Fix zeros_like signature

- onnxscript/function_libs/torch_lib/ops/core.py
Rename variables to be more informative and maintainable.
> Fix Op (aten::flatten) | feat(torchlib)

- onnxscript/function_libs/torch_lib/ops/core.py
> [torchlib] Simplify `aten.prelu`

- onnxscript/function_libs/torch_lib/ops/core.py
- tests/function_libs/torch_lib/ops_test_data.py
Also simplify pixel_shuffle implementation.
Fixes https://github.com/onnx/onnx/issues/6162
> [torchlib] Implement pixel unshuffle

- onnxscript/ir/__init__.py
- onnxscript/ir/_external_data.py
- onnxscript/ir/_external_data_test.py
Fix https://github.com/microsoft/onnxscript/issues/1696
> [IR] Pass to offload external tensors

- onnxscript/function_libs/torch_lib/ops/nn.py
- tests/function_libs/torch_lib/extra_opinfo.py
> Fix Ops (aten::_scaled_dot_product_efficient_attention) | feat (torchlib)

- onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/function_libs/torch_lib/ops/nn.py
Trace commonly used activation functions and fix elu
> [torchlib] Trace some activation functions

- onnxscript/function_libs/torch_lib/ops/core.py
1. Handle baddbmm when scalars are SymFloat
2. Accept bool as scalar_tensor input
Fixes https://github.com/justinchuby/torch-onnx/issues/42
> Fix baddbmm and scalar_tensor

- onnxscript/function_libs/torch_lib/ops/core.py
> [torchlib] Mark add/sub as trace_only

- onnxscript/ir/_core.py
I mistakenly duplicated all functions many times.
> [IR] Fix bug in Model str method

- docs/tutorial/rewriter/examples/allow_other_attributes.py
- docs/tutorial/rewriter/rewrite_patterns.md
Update documentation to illustrate the use of attributes in patterns. Fixed the auto-generated files manually. (Must experiment on how to instruct copilot to improve its first attempt.)
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/microsoft/onnxscript?shareId=3f6981af-52ef-46dd-9dac-7e8d98e499bb).
> Add example for attributes in rewriter tutorial

- onnxscript/optimizer/__init__.py
- onnxscript/optimizer/_inliner.py
- onnxscript/optimizer/optimizer_test.py
Initial version of IR-based optimizer (avoids conversion to Proto).
Still to be evaluated/debugged with real models. Adding here to enable experimentation with benchmark models.
> IR optimizer

- onnxscript/optimizer/_inliner.py
Details in https://github.com/microsoft/onnxscript/issues/1858
> Fix #1858 for Python 3.8 support

- onnxscript/function_libs/torch_lib/ops/core.py
Fix https://github.com/pytorch/pytorch/issues/135532
> [torchlib] Fix aten_empty_like

- onnxscript/function_libs/torch_lib/ops/core.py
Add some missing operators from https://github.com/pytorch/pytorch/issues/136524 /cc @justinchuby
> [torchlib] Support mod and eq on SymInt

- onnxscript/ir/_core.py
- onnxscript/optimizer/_constant_folding.py
Fix bug introduced while migrating cast-logic to new IR in optimizer.
> Fix cast inference bug

- onnxscript/function_libs/torch_lib/ops/core.py
Simplify aten_sum_dim_IntList by removing the script functions.
> [torchlib] Simplify aten_sum_dim_IntList

- onnxscript/function_libs/torch_lib/ops/core.py
> [torchlib] Add memory_format to ones_like

- onnxscript/function_libs/torch_lib/ops/core.py
> [torchlib] Make matmul trace_only

- .azure-pipelines/_release-template.yml
Clarify what each step is doing by fixing their names
> Update _release-template.yml step names

- onnxscript/function_libs/torch_lib/ops/core.py
- onnxscript/function_libs/torch_lib/ops/nn.py
Trace ops discovered in https://github.com/pytorch/pytorch/issues/147617 and simplify `repeat` implementation.
> [torchlib] Trace several ops

- onnxscript/_framework_apis/torch_2_6.py
Enable version converter for torch>=2.6
> Enable version converter for torch>=2.6

- onnxscript/rewriter/ort_fusions/sdpa.py
- onnxscript/rewriter/ort_fusions/sdpa_test.py
Add tests for:
- Pre-mul
- Post-div
- Post-mul
> Extend sdpa tests

- onnxscript/rewriter/ort_fusions/sdpa.py
- onnxscript/rewriter/ort_fusions/sdpa_test.py
- Add spda rules and tests for unmasked patterns
- Fix parameterized import
> Add spda rules and tests for unmasked patterns

- onnxscript/converter.py
- onnxscript/values.py
Remove a couple of warning messages in onnxscript that hasn't been useful so far and is typically a distraction.
> Remove warning messages

- README.md
- setup.py
onnxscript.ai is not working so fix some links in the meantime.
> Update onnxscript documentation page

- onnxscript/rewriter/ort_fusions/skip_normalization_test.py
> Temporarily skip the whisper test in skip layernorm fusion

- onnxscript/backend/onnx_export.py
- onnxscript/ir/_core.py
- onnxscript/ir/_core_test.py
- onnxscript/optimizer/_constant_folding.py
- onnxscript/version_converter/_version_converter.py
TODO: Also update opset_imports to handle the "ai.onnx" key.
Fix https://github.com/microsoft/onnxscript/issues/2280
> [IR] Normalize "ai.onnx" domain to ""

- onnxscript/rewriter/_rewrite_rule.py
Fix change of RewriteRuleAsClass to RewriteRuleClassBase within comment.
> Fix rename within comments

- onnxscript/rewriter/ort_fusions/_core.py
From https://github.com/microsoft/onnxscript/pull/2317.
> Disable fused_matmul_rule_sets

- .azure-pipelines/publish.yml
Rename job names and use an environment for approvals
> Update publish pipeline to use an environment

- noxfile.py
- onnxscript/optimizer/_optimizer.py
> [pass][reland] Enable DeduplicateInitializersPass

- tests/function_libs/torch_lib/e2e_ops_tests.py
> Add a test for boolean attention mask within SDPA

- onnxscript/rewriter/ort_fusions/_core.py
There are specific optimization needs from ort shipping models.
> Add ort-specific passes to ort_fusion

- onnxscript/rewriter/rules/common/_fuse_conv_affine_test.py
> Remove usages of ir.Input in test
